### PR TITLE
Docs v2.0.0-alpha.9

### PR DESCRIPTION
**Pull request by RingerJK**
**Docs v2.0.0-alpha.9**<br/><br/>**cc** @mapbox/navigation-android

### CODE REVIEW

**Review by colleenmcginnis — COMMENTED** [review]
The `UI Resources` and `UI Utils` pages are empty. Is that expected?

**Comment by RingerJK** [comment]
> The `UI Resources` and `UI Utils` pages are empty. Is that expected?

great catch! Resolved in https://github.com/mapbox/mapbox-navigation-android/pull/4030. 
This week we'll make a new release of `2.0.0-alpha.10`. Does the new docs version substitute `2.0.0-alpha.9`? If so we should be good to merge it

**Comment by colleenmcginnis** [comment]
>This week we'll make a new release of 2.0.0-alpha.10. Does the new docs version substitute 2.0.0-alpha.9?

We can replace it in the list of version numbers in the android docs repo when alpha.10 is available.

**Review by colleenmcginnis — APPROVED** [review]

**Comment by RingerJK** [comment]
legacy

**Pull request closed without merging**
