### PR TITLE
Update Maps SDK 5.5.0

### PR DESCRIPTION
**Pull request by danesfeder**

### CODE REVIEW

**Comment by baversjo** [comment]
@danesfeder Trying to get `mapbox-android-navigation-ui` working in my android app, 
but a okhttp issue is causing your library to fail initiating. 
It was fixed "for 5.5.0": https://github.com/mapbox/mapbox-gl-native/issues/11371
And I believe this merge should resolve the issue in `mapbox-navigation-android`.
I see that https://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-navigation-ui/0.11.0-SNAPSHOT/ was just updated after this merge, is it supposed to contain the fix? I've tried to clear my gradle cache and specify `com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.11.0-SNAPSHOT` but it's still failing with the same exception:

```
 java.lang.NoSuchMethodError: No static method toHumanReadableAscii(Ljava/lang/String;)Ljava/lang/String; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in 
```

What version of this lib is supposed to be stable?

**Comment by danesfeder** [comment]
Hey @baversjo, where are you seeing this error while using the UI library?  The most recent stable version is `0.10.0` but we build SNAPSHOTS (like you saw with this PR) every time we merge into `master`.  These versions are not always stable, as master is constantly being updated / changed.

**Comment by baversjo** [comment]
@danesfeder It crashed on this line in my code (the first use of the mapbox libs):
```navigation = new MapboxNavigation(this, MAPBOX_ACCESS_TOKEN);```
I will try 0.10.0, thanks.

**Comment by baversjo** [comment]
@danesfeder Verified I got 0.10.0 installed, but I still get the same issue with 0.10.0. Probably because it downloads the latest version of OKHTTP? Does #738 resolve the issue you think?

**Comment by danesfeder** [comment]
@baversjo yes it should.  OkHTTP was updated and broke the builds.  Stay tuned for that to merge and a stable `0.11.0` release if you'd rather not use the SNAPSHOT.  Thanks for your patience here.

**Comment by danesfeder** [comment]
@baversjo https://github.com/mapbox/mapbox-navigation-android/pull/738 just landed.  Keep an eye out for `0.11.0`

**Pull request merged**
