### PR TITLE
updated mapbox-java to v6.9.0-beta.1

### PR DESCRIPTION
**Pull request by LukasPaczos**

### CODE REVIEW

**Review by Zayankovsky — APPROVED** [review]

**Comment by LukasPaczos** [comment]
With the update and introduction of https://github.com/mapbox/mapbox-java/pull/1500 we're starting to run into https://github.com/mockk/mockk/issues/255 whenever a `toBuilder` function is called (or even tried to be mocked) on a `DirectionsJsonObject`. Looks like something in the structure of the class with nested public abstract functions is tripping mockk up.

**Comment by dzinad** [comment]
> With the update and introduction of https://github.com/mapbox/mapbox-java/pull/1500 we're starting to run into https://github.com/mockk/mockk/issues/255 whenever a toBuilder function is called (or even tried to be mocked) on a DirectionsJsonObject. Looks like something in the structure of the class with nested public abstract functions is tripping mockk up.

Oooh, can we workaround the issue? Use real objects for instance. For classes like `DirectionsJsonObject` we usually just need some return values, no verifying or stubbing the answer in a complicated manner.
It may ask for some required properties of course but we can make a utility method for that to avoid copy-paste of unnecessary in this specific test data.

**Comment by LukasPaczos** [comment]
> Oooh, can we workaround the issue?

I think so, I pushed a new commit with a workaround that includes real instances and spies. Seems to work fine but definitely a little bit inconvenient.

**Comment by LukasPaczos** [comment]
Well, I was over-optimistic, looks like there are _many_ more occurrences of that in the test than the initial run uncovered.

**Comment by dzinad** [comment]
> Well, I was over-optimistic, looks like there are many more occurrences of that in the tests than the initial run uncovered.

Not too many, I've tried to fix them.

**Comment by LukasPaczos** [comment]
> Not too many, I've tried to fix them.

Nice, thank you! I only glanced late Friday and the output was looking intimidatingly long (nearly 50 tests failing). Let me clean up the last pieces and we can merge.

**Review by dzinad — APPROVED** [review]

**Pull request merged**
