### PR TITLE
Docs v2.0.0-beta.16

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Docs for release v2.0.0-beta.16

### CODE REVIEW

**Review by colleenmcginnis — COMMENTED** [review]
The docs themselves look ok to me. I did notice there are a few files being added outside the `2.0.0-beta.16` folder:

- `libnavigation-core/src/main/assets/sdk_versions/com.mapbox.navigation.core`
- `libnavigation-core/src/test/resources/mobile-event-schemas.jsonl.gz`
- `libnavui-base/src/main/assets/sdk_versions/com.mapbox.navigation.ui.base`
- `libnavui-maneuver/src/main/assets/sdk_versions/com.mapbox.navigation.ui.maneuver`
- `libnavui-maps/src/main/assets/sdk_versions/com.mapbox.navigation.ui.maps`
- `libnavui-resources/src/main/assets/sdk_versions/com.mapbox.navigation.ui.resources`
- `libnavui-speedlimit/src/main/assets/sdk_versions/com.mapbox.navigation.ui.speedlimit`
- `libnavui-tripprogress/src/main/assets/sdk_versions/com.mapbox.navigation.ui.tripprogress`
- `libnavui-util/src/main/assets/sdk_versions/com.mapbox.navigation.ui.utils`
- `libnavui-voice/src/main/assets/sdk_versions/com.mapbox.navigation.ui.voice`
- `publish_api_docs_android.sh`

Is that intentional? (Most other docs PRs only include content within the version folder.)

**Comment by Guardiola31337** [comment]
@cafesilencio weren't those removed? If not could you push a commit removing them?

**Comment by cafesilencio** [comment]
The files have been removed.

**Comment by Guardiola31337** [comment]
@colleenmcginnis could you re-check when you have a chance? 🙏

**Review by colleenmcginnis — APPROVED** [review]

**Pull request merged**
