### PR TITLE
Resetting the trim-offset to 0.0 when routes are drawn. 

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Fixing a bug found when using the trim-offset feature.  It appears the trim-offset must be explicitly reset to 0.0.  Setting a line gradient on the layer isn't enough to change the line's appearance.

### CODE REVIEW

**Comment by cafesilencio** [comment]
I'm adding a quick fix in the internal testing app. so maybe we want to wait for a fix from the GL team rather than merging this.

**Review by LukasPaczos — COMMENTED** [review]
This change makes sense to me 👍 Could you add tests? Let's cherry-pick to the v2.5 release branch later.

**Comment by cafesilencio** [comment]
I don't think it's safe to assume this is a valid fix.  The business rules are applied in the `MapboxRouteLineApi` class.  That is where a decision is made about the lines' appearance.  The render method where this change was made isn't reserved for setting new route exclusively. For example when traffic is updated the result will be sent to the same render method which would reset the trim-offset to 0 but that would be wrong if a traffic update occurred halfway through a route.  

I think it's better to get a real fix from the GL team rather than including something like this without more thought and testing.

**Comment by LukasPaczos** [comment]
In my opinion, we're misusing the `line-trim-offset` currently. Previously, we controlled the color and vanishing effect of the line with one property, the `line-gradient`. Now for the same control we need to use two properties, `line-gradient` (or `line-color`) and `line-trim-offset`. We shouldn't expect GL-Native to merge these two together for us, Nav SDK needs to correctly adapt to this change which in practice means that the offset point needs be controlled independently from the color of the line. 

If the currently proposed change doesn't work, let's find a different way. Maybe we could bundle the offset information in `RouteSetValue`?

**Comment by cafesilencio** [comment]
> ...we could bundle the offset information in RouteSetValue...

That's what I"m exploring.

I don't think we're misusing `line-trim-offset`. It is already coupled to the gradient since it can't be used without it. Furthermore the `line-trim-offset` doesn't suit our needs.  It doesn't support a color option and it doesn't support multiple stops.

**Comment by LukasPaczos** [comment]
Rebased to fix the conflicts and added missing docs so that we can merge and CP for v2.5.0-rc.3.

**Comment by LukasPaczos** [comment]
Making two additional changes:
- First, make the new `RouteLineTrimOffset` class `internal` because Dokka misbehaves and doesn't produce the documentation (https://github.com/mapbox/mapbox-navigation-android/issues/5851) and we don't really need to make this class public right now, we can always expose it later if needed.
- Second, move the `RouteLineTrimOffset` to an `.internal` package because even though the class is public, Metalava still produced entries in API files (https://github.com/mapbox/mapbox-navigation-android/issues/5852).

Looks like the way `value classes` are compiled causes some problems for our tooling.

**Review by LukasPaczos — APPROVED** [review]

**Comment by cafesilencio** [comment]
We should try to get that class back to a public state at some point. With it being internal it can't be overridden via RouteLineDynamicData::toMutable() like the other items in that class. :(

**Comment by Guardiola31337** [comment]
> We should try to get that class back to a public state at some point. With it being internal it can't be overridden via RouteLineDynamicData::toMutable() like the other items in that class. :(

Addressed in https://github.com/mapbox/mapbox-navigation-android/pull/5858

**Comment by Guardiola31337** [comment]
> We should try to get that class back to a public state at some point. With it being internal it can't be overridden via RouteLineDynamicData::toMutable() like the other items in that class. :(

Addressed in https://github.com/mapbox/mapbox-navigation-android/pull/5858

**Pull request merged**
