### PR TITLE
Automatic recenter

### PR DESCRIPTION
**Pull request by siavashabdoli**
The camera will be recenter in case of user don't scroll for 15 sec

### CODE REVIEW

**Comment by siavashabdoli** [comment]
@danesfeder Hi, Are you going to merge this branch? should i do anything? I requested for merge two weeks ago. let me know if I should change anything or close if you don't want to merge it

**Comment by danesfeder** [comment]
Hey @siavashabdoli, sorry for the delay here.  We will give this some 👀 this week and leave some comments.  I think this is a cool feature to add to the turn-by-turn UI.  Thank you very much for the contribution!

cc @Guardiola31337 @devotaaabel

**Comment by siavashabdoli** [comment]
@danesfeder Hi. did you guys check that? consider I deleted all of the logic part from navigationview and delete all check for navigationpresenter != null because I moved preseter init into constructor

**Comment by siavashabdoli** [comment]
@Guardiola31337 @devotaaabel Hi :) did you check this? if you have comment on this tell me so I can fix that or add that ability to that :) another point is I rewrite some presenter releated things in order to move all logic to presenter. but during the time I think some changes has been applied to view and presenter so now maybe there's some problem in it :) every time I update and fix my branch but it's now like lots of time i'm waiting for comment :) if you find it helpful tell me and I will update and fix the branch in less than one day and then let you know ;) thanks a lot :)

**Comment by siavashabdoli** [comment]
it was resolved in new versions(14 or 15)

**Pull request closed without merging**
