### PR TITLE
Sb 246 migrate to updated dynamic camera

### PR DESCRIPTION
**Pull request by cafesilencio**
## Description
In response to: https://github.com/mapbox/navigation-sdks/issues/246

This work was to get the DynamicCamera working with the 1.0 SDK code base. There was a need to set the camera in the UI code without exposing it to core. I think this is needed to ensure others are not blocked in working on other UI compatibility tickets. More work may need to be done on this but I think this is a step forward allowing others to  continue with the compatibility effort.

### CODE REVIEW

**Comment by cafesilencio** [comment]
When we originally discussed (here in SF) our strategy for the UI SDK work, getting the example apps. working was on the todo list. As getting the camera updated within the SDK would be blocking that effort I wanted to get this out of the way as soon as possible. Any chance this PR can get approved without including an example app. so that we can divide the work of getting the example apps working rather that myself being the bottleneck? I'll take responsibilities for any bugs in this PR that need to be addressed.

**Comment by Guardiola31337** [comment]
@cafesilencio 
> When we originally discussed (here in SF) our strategy for the UI SDK work, getting the example apps. working was on the todo list. As getting the camera updated within the SDK would be blocking that effort I wanted to get this out of the way as soon as possible. Any chance this PR can get approved without including an example app. so that we can divide the work of getting the example apps working rather that myself being the bottleneck? I'll take responsibilities for any bugs in this PR that need to be addressed.

Ohh I didn't mean to migrate all of the examples. I meant to add a quick sanity test to any of the existent examples to verify that the changes introduced bring the camera feature to the `1.0` UI (`libnavigation-ui`). In any case, if that was already discussed and we agreed on following up we can definitely merge here 🚀 Sorry for the confusion.

Minor comment. Clean up / smaller commits like `fixed checkstyle violations`, `ran make license in response to CI failure` or `removed comment and line of code no longer needed for compatability...` could be rebased for a cleaner history. Could you fixup and rebase when you have a chance?

**Comment by abhishek1508** [comment]
LGTM 🚀 except for the comments above

**Comment by cafesilencio** [comment]
this issue can be closed

**Comment by Guardiola31337** [comment]
@cafesilencio you mean #2483? Feel free to close yourself if we're good to do so 🚀

**Pull request merged**
