### PR TITLE
Fix the null pointer better

### PR DESCRIPTION
**Pull request by kmadsen**
## Description

resolves: https://github.com/mapbox/mapbox-navigation-android/issues/2716

I fixed a crash by only checking for `null` here. But downstream requires `geometry`.

Update the tests to reflect this, and fix it. Thanks for finding @abhishek1508!

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

## Testing

Please describe the manual tests that you ran to verify your changes

- [ ] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by kmadsen** [comment]
https://github.com/mapbox/mapbox-navigation-android/issues/2716#issuecomment-612270636

We're discussing if this is the best place to fix this. The stack trace looks like this

1. MapRouteProgressChangeListener 
2. MapRouteLine
3. FeatureProcessingTask (crashes when geometry is null)

**Comment by abhishek1508** [comment]
Looking at `MapRouteLine#draw`
```
void draw(DirectionsRoute directionsRoute) {
    List<DirectionsRoute> route = new ArrayList<>();
    route.add(directionsRoute);
    draw(route);
}
```

I would suggest that we make sure either we don't pass `null` `directionRoute`
or if we do we make sure to add a null check, because it doesn't makes sense to draw a route on the map if the route is null

**Comment by kmadsen** [comment]
This fix doesn't feel right. 

> Looking at `MapRouteLine#draw`
> 
> ```
> void draw(DirectionsRoute directionsRoute) {
>     List<DirectionsRoute> route = new ArrayList<>();
>     route.add(directionsRoute);
>     draw(route);
> }
> ```
> 
> I would suggest that we make sure either we don't pass `null` `directionRoute`
> or if we do we make sure to add a null check, because it doesn't makes sense to draw a route on the map if the route is null
> cc @kmadsen

MapRouteLine needs a lot of ❤️ . Right now we'll try to fix and not break anything new.

Added tests to cover all our concerns we covered.

**Comment by abhishek1508** [comment]
The branch still crashes
Steps to reproduce
1. Open SimpleMapboxNavigation
2. Long press at any point in the map
3. Click on Start Navigation
4. Click on Clear Routes

**Expexted:**
The app shouldn't crash

**Actual**
The app crashes

**Stacktrace**

```
2020-04-10 18:44:02.818 7327-7327/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 7327
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
        at com.mapbox.navigation.ui.route.MapRouteArrow.addUpcomingManeuverArrow(MapRouteArrow.java:114)
        at com.mapbox.navigation.ui.route.MapRouteProgressChangeListener.onProgressChange(MapRouteProgressChangeListener.kt:30)
        at com.mapbox.navigation.ui.route.MapRouteProgressChangeListener.onRouteProgressChanged(MapRouteProgressChangeListener.kt:17)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:289)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:31)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:267)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
cc @kmadsen

**Comment by kmadsen** [comment]
@abhishek1508 https://github.com/mapbox/mapbox-navigation-android/issues/2716#issuecomment-612281297

Something else introduced the issue of having no `geometry`

**Comment by kmadsen** [comment]
Looks like whatever caused it upstream, is exposing all the issues downstream

**Comment by kmadsen** [comment]
`MapRouteArrow` also not obeying nullable classes

Screen Shot 2020-04-10 at 6 52 37 PM

**Comment by kmadsen** [comment]
It appears the `MapRouteArrow` will need to be fixed there, because it handles its own state changes with routes. So we can call that a separate issue, doesn't seem like we can fix it from `MapRouteProgressChangeListener`

https://github.com/mapbox/mapbox-navigation-android/blob/91a935f5f47c5d35240e7a5ffb1198da2d2eca06/libnavigation-ui/src/main/java/com/mapbox/navigation/ui/route/MapRouteArrow.java#L113-L119

**Comment by abhishek1508** [comment]
Going to open a new PR to fix https://github.com/mapbox/mapbox-navigation-android/pull/2754#issuecomment-612294149

**Pull request merged**
