### PR TITLE
Fix Checkstyle compile issues.

### PR DESCRIPTION
**Pull request by abhishek1508**
## Description

Fix checkstyle compile issues for checkstyle v8.26 and above.

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Fix checkstyle compile issues for checkstyle v8.26 and above.

### Implementation

Fix checkstyle compile issues for checkstyle v8.26 and above.

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by JunDai** [comment]
I don't add the checkstyle at my side. 
What's the compile error and how this PR could fix it? I mean, from the code diff, it seems just move the code from one place to another.

**Comment by abhishek1508** [comment]
@JunDai We should all follow these steps
https://github.com/mapbox/mapbox-gl-native-android/wiki/Setting-up-Mapbox-checkstyle.

When you try to follow them you will see that Android studio reports error in `checkstyle.xml`

**Comment by Guardiola31337** [comment]
@abhishek1508 
> I don't add the checkstyle at my side. So I don't know what's the compile error and how this PR could fix it? I mean, from the code diff, it seems just move the code from one place to another.

Yeah, how's that possible? And how can moving code around makes CI (`checkstyle`) to fail? 🤔

cc @JunDai

**Comment by abhishek1508** [comment]
checkstyle v8.26 and above 

```
<!-- 100 char per line max, unless unavoidable -->
    <module name="LineLength">
        <property name="max" value="120"/>
        <property name="ignorePattern"
            value="^package.*|^import.*|a href|href|http://|https://|ftp://"/>
    </module>
```

cannot have `LineLength` inside `TreeWalker`.
It needs to be live directly inside `Checker` tag

**Comment by JunDai** [comment]
FYI that the error is:
```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)

**Comment by Guardiola31337** [comment]
Got it! It comes from the bumping Checkstyle version. Thanks for clarifying @abhishek1508 🚀

**Pull request merged**
