### PR TITLE
Refactoring based on updated architectural format.

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Refactors the trip progress component based on the recent architectural discussions and agreements.

### Changelog
```
<changelog>Refactored Trip Progress component and altered API.</changelog>
```

### CODE REVIEW

**Review by abhishek1508 — APPROVED** [review]
LGTM 💯

**Comment by LukasPaczos** [comment]
:rocket: Migration guide doesn't even need any updates, does it?

**Comment by cafesilencio** [comment]
Nope. Bonus!

**Comment by LukasPaczos** [comment]
easy

**Pull request merged**
