### PR TITLE
Make ui robo tests use debug

### PR DESCRIPTION
**Pull request by kmadsen**
## Description

https://github.com/mapbox/mapbox-navigation-android/issues/3562

I think the release mode is obfuscating these stack traces.

- [ ] I have added any issue links
- [ ] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

## Testing

Please describe the manual tests that you ran to verify your changes

- [ ] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make core-update-api` (Core) / `$> make ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs

### CODE REVIEW

**Review by RingerJK — APPROVED** [review]
LGTM 👍

**Review by LukasPaczos — CHANGES_REQUESTED** [review]
The robo test is intentionally run in a release mode to test progaurd integration.

There might be a way to upload [proguard mappings](https://developer.android.com/studio/build/shrink-code#decode-stack-trace) to firebase during a robo run, if not, we can [store the mappings on CI](https://circleci.com/docs/2.0/artifacts/) for each robo run and match the symbols manually if there's a crash.

**Comment by RingerJK** [comment]
> The robo test is intentionally run in a release mode to test progaurd integration.
> 
> There might be a way to upload [proguard mappings](https://developer.android.com/studio/build/shrink-code#decode-stack-trace) to firebase during a robo run, if not, we can [store the mappings on CI](https://circleci.com/docs/2.0/artifacts/) for each robo run and match the symbols manually if there's a crash.

@LukasPaczos We can [Optimize without obfuscate](https://medium.com/mobile-app-development-publication/optimize-without-obfuscate-your-debug-build-49bf5a56df3f). Need some changes with gradle but it's not a huge one 

**cc** @kmadsen

**Comment by LukasPaczos** [comment]
We want to obfuscate as well though and test the default proguard rules that we're shipping with our artifacts.

**Comment by RingerJK** [comment]
> We want to obfuscate as well though and test the default proguard rules that we're shipping with our artifacts.

yes yes, I know. We could apply it for Debug only(event for Debug on CI only)

**Comment by LukasPaczos** [comment]
Adding perf optimizations increases the build time, so we'd be fighting against that trade-off. Not sure if it's worth it.

**Comment by kmadsen** [comment]
@LukasPaczos do you have another proposal for investigating issues such as this? https://github.com/mapbox/mapbox-navigation-android/issues/3562

**Comment by LukasPaczos** [comment]
@kmadsen my alternative ideas are in https://github.com/mapbox/mapbox-navigation-android/pull/3563#pullrequestreview-487613960. Hopefully, Firebase can handle it for us, if not, uploading the mapping to CI pipeline and verifying ourselves is always an option.

**Comment by kmadsen** [comment]
> We want to obfuscate as well though and test the default proguard rules that we're shipping with our artifacts.

Ok going to go with optimizing for proguard.

> @ kmadsen my alternative ideas are in #3563 (review). Hopefully, Firebase can handle it for us, if not, uploading the mapping to CI pipeline and verifying ourselves is always an option.

Uploading the mapping to CI and verifying ourselves, that's a larger task than removing the obfuscation. But will let the discussion head in that direction, closing this

**Pull request closed without merging**
