### PR TITLE
Adding 1.1.0 stable release API ref docs

### PR DESCRIPTION
**Pull request by langsmith**
## Description

This pr adds stable `1.1.0` release API ref docs to this repo's `publisher-production` branch so that they can eventually be viewed at https://docs.mapbox.com/android/navigation/api-reference/

- [ ] I have added any issue links
- [ ] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

### CODE REVIEW

**Comment by langsmith** [comment]
@danswick , not sure if you're familiar with the CI 💥 on this pr (https://circleci.com/docs/2.0/). Expected and can be ignored?

Screen Shot 2020-10-08 at 1 34 34 PM

**Comment by danswick** [comment]
Should be ok, @langsmith! if you want to be extra sure, you can force push `ls-1.1.0-release-api-ref-docs` to `publisher-staging` just to test, but these docs branches don't rely on any automated tests from CI. 

You can also tell circle to skip by putting `[ci skip]` in your commit message like https://github.com/mapbox/mapbox-gl-native-ios/blob/main/scripts/docs-update-maps.sh#L35.

**Comment by langsmith** [comment]
Ok, I'm fine merging as is.....once I get a ✅ from the sole reviewer 😬

**Review by danswick — APPROVED** [review]
lgtm, @langsmith

**Comment by langsmith** [comment]
OH! I forgot to ask. Do any other changes to CSS/HTML files need to be made? I copy/pasted files the generated files into this pr's `1.1.0` core and ui folders, but didn't do anything else other than manually adjusting the version numbers in the top-level `index.html` files.

**Comment by danswick** [comment]
My mistake. I forgot that the Dokka docs need to be formatted. I can do that and commit to this branch. Sound ok to you, @langsmith?

**Comment by langsmith** [comment]
Sounds good @danswick

**Pull request merged**
