### PR TITLE
Add MapboxSpeechApiExtension for generation files

### PR DESCRIPTION
**Pull request by VitaminPSG**
### Description

As a user, I want to manage file uploads.

In the current implementation, there is no way to download multiple files at the same time.

The extension allows you to start the generation process without interrupting the current tasks

### Changelog

```
<changelog>Add MapboxSpeechApiExtension for generation files</changelog>
```

### CODE REVIEW

**Review by Guardiola31337 — COMMENTED** [review]
Thanks for bringing this up @VitaminPSG

We should discuss how we want to tackle this as there are other features (`Api`s) already having the same issue. For instance `MapboxManeuverApi`. On the contrary, we're currently supporting it for `MapboxJunctionApi` and `MapboxSignboardApi` (only `cancelAll`).

I'd say we should consolidate these and implement something similar to `MapboxJunctionApi` and `MapboxSignboardApi` for `MapboxSpeechApi` and `MapboxManeuverApi` and add support for canceling by request to `MapboxJunctionApi` and `MapboxSignboardApi` for consistency.

Also, on the topic of exposing suspendable functions publicly we have an on-going discussion here https://github.com/mapbox/mapbox-navigation-android/issues/4126 Please chime in and provide any feedback you may have 🙏 

cc @mapbox/navigation-android

**Comment by zugaldia** [comment]
Now that https://github.com/mapbox/mapbox-navigation-android/issues/4432 has landed, should we revisit this PR in the context of https://github.com/mapbox/mapbox-navigation-android/issues/4403?

**Comment by Guardiola31337** [comment]
@VitaminPSG this is going to be superseded by https://github.com/mapbox/mapbox-navigation-android/pull/4646, right? Feel free to close here if so.

**Comment by VitaminPSG** [comment]
Close. Done in https://github.com/mapbox/mapbox-navigation-android/pull/4646.

**Pull request closed without merging**
