### PR TITLE
Move events from telemetry to nav sdk

### PR DESCRIPTION
**Pull request by Chaoba**
## Description
fixes [#204](https://github.com/mapbox/mapbox-events-android/issues/204)
Move nav event related codes from telemetry to nav sdk.

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal
- [x] Move nav event related codes from telemetry to nav sdk.
- [x] Polish the original codes.
- [x] Add test cases 
- [x] bump telemetry sdk

### Implementation

Please include all the relevant things implemented and also rationale, clarifications / disclaimers etc. related to the approach used. It could be as self code companion comments

## Screenshots or Gifs

Please include all the media files to give some context about what's being implemented or fixed. It's not mandatory to upload screenshots or gifs, but for most of the cases it becomes really handy to get into the scope of the feature / bug being fixed and also it's REALLY useful for UI related PRs screenshot gif

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed)
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Dump all nav events to staging and make sure they are properly ingested.
  - [x] Arrive event
  - [x] Cancel event
  - [x] Depart event
  - [x] Feedback event
  - [x] Reroute event
## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by Chaoba** [comment]
@danesfeder Thanks for your reminding, will do.

**Comment by Chaoba** [comment]
@danesfeder @Guardiola31337 Any idea on how to fix the build error?

**Comment by andrlee** [comment]
@Chaoba can you add one more item to your testing checklist: dump all nav events to staging and make sure they are properly ingested.

**Comment by Chaoba** [comment]
> @Chaoba can you add one more item to your testing checklist: dump all nav events to staging and make sure they are properly ingested.

@andrlee Done.

**Comment by Chaoba** [comment]
@andrlee Where could we check all nav events are properly ingested?

**Comment by Chaoba** [comment]
@danesfeder For proguard, I don't find any rules may related with this PR and for events, currently I have some troubles in verifying events are correctly sent. We could get 204 for sending events, but can't verify it on Mode as described [here](https://mapbox.slack.com/archives/C7Q68N7M3/p1557123427053100)

**Comment by Chaoba** [comment]
@danesfeder @andrlee Could take a look at this PR again? Thanks.

**Comment by tobrun** [comment]
@mapbox/navigation-android what is needed to get this PR moving?

**Comment by Thomas740** [comment]
Guardiola31337

**Comment by Thomas740** [comment]
#204

**Comment by Guardiola31337** [comment]
@Chaoba 
> but can't verify it on Mode as described here

I've tested in staging and checked that events showed up in Mode and look consistent, we're good to merge here 🚀  

I noticed https://github.com/mapbox/mapbox-navigation-android/issues/1992 but it's not blocking this PR, we can fix separately.

Could you 👀 and re-run CI so we can merge? I've pushed some changes and CI didn't fire off. I also tried to re-run it manually, but GitHub didn't catch it either 🤔

**Comment by Guardiola31337** [comment]
cc @andrlee

**Comment by Guardiola31337** [comment]
> Could you 👀 and re-run CI so we can merge? I've pushed some changes and CI didn't fire off. I also tried to re-run it manually, but GitHub didn't catch it either 🤔

This is fixed now 👀 https://github.com/mapbox/mapbox-navigation-android/pull/1993 🎉 

@Chaoba Feel free to merge when you have a chance. Thanks again!

cc @andrlee

**Comment by Guardiola31337** [comment]
Going ahead and merging here.

Thanks again @Chaoba 

cc @andrlee @abhishek1508

**Pull request merged**
