### PR TITLE
[WIP] Fix offRoute false positive

### PR DESCRIPTION
**Pull request by Grsmto**
Hi guys,
Opening this PR to try to fix the offRoute event being triggered at wrong moment (#274).
I was able to reproduce the issue with the Navigation UI activity as well.

This is a WIP. I'd like someone to have a look at it cause I think I'm not able to fix this by myself. Just trying here help a bit the process.

### CODE REVIEW

**Comment by cammace** [comment]
Hey @Grsmto, we recently merged a few PRs that worked on the off-route logic along with the snap to route logic. These I believe should fix your issue, let me know when you do your next test drive :)

**Comment by Grsmto** [comment]
Hey @cammace I'll definitely try that! Thanks.

**Comment by cammace** [comment]
Any update on the @Grsmto? Are you still running into this issue or can we close this?

**Comment by Grsmto** [comment]
Hey @cammace as this PR is related to #274 and #293 from my testing I'm still having these issues. 
But I only tested with the mock location, I didn't test in test drive as I still had it with the mock.
I doubt I will find a solution myself and as you guys worked on this already I think we can close this PR.

**Pull request closed without merging**
