### PR TITLE
`Def`s retention policy review

### LINKED ISSUE #4145: Review `Def`s retention policy in SDK codebase
Retention policy of `Def`s for public API must be `RUNTIME`(rare `BINARY`) and for non-public `SOURCE`

https://github.com/mapbox/mapbox-navigation-android/blob/e5bba10551ff58626279446f6393e71d00728d22/libnavigation-core/src/main/java/com/mapbox/navigation/core/trip/model/roadobject/reststop/RestStopType.kt#L30-L36

**cc** @Guardiola31337

### PR DESCRIPTION
**Pull request by RingerJK**
### Description
`Def`s' retention policy review

Closes #4145

### CODE REVIEW

**Review by Guardiola31337 — APPROVED** [review]
LGTM

BTW curious where's 

> Retention policy of `Def`s for public API must be `RUNTIME`(rare `BINARY`) and for non-public `SOURCE`

recommendation coming from? Trying to understand why it should be `RUNTIME` instead of `SOURCE` 🤔 

Could you clarify?

**Comment by LukasPaczos** [comment]
I want to join @Guardiola31337's question like I mentioned during the standup - is there a specific recommendation for this approach?

Retaining an annotation in runtime allows for it to be inspected with reflection, is there a specific request for this feature? Otherwise, we might be unnecessarily increasing the binary size.

**Comment by RingerJK** [comment]
> recommendation coming from? Trying to understand why it should be RUNTIME instead of SOURCE 🤔

> I want to join @Guardiola31337's question like I mentioned during the standup - is there a specific recommendation for this approach?

`RUNTIME` and `BINARY` are stored into binary output, I think that is what we want, isn't it? 🤔 https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.annotation/-annotation-retention/

> Retaining an annotation in runtime allows for it to be inspected with reflection, is there a specific request for this feature? Otherwise, we might be unnecessarily increasing the binary size.

We have `9` `StringDef`s and `10` `IntDef`s, which is not really affecting binary size, I wouldn't worry about it. 
We don't have a `rule` for `Retention`, where to use one or another. Via the PR I'd introduce the same approach, to be consistent in the whole SDK.
Btw I'm ok to replace `RUNTIME` by `BINARY` as we don't have specific requests for that.

**Comment by LukasPaczos** [comment]
If we use `SOURCE`, would developers still be able to take advantage of that annotation in their builds (get IDE/lint warnings when they provide a wrong type value)? If the answer is yes, then that's what we should go for, we probably shouldn't optimize for reflection use cases.

**Comment by RingerJK** [comment]
`SOURCE` is visible in `java`, not visible in `class` files, so when IDE suggests a value for a method signature `SOURCE` is not suggested, for `BINARY` and `RUNTIME` it works.

`com.google.android.material.chip.ChipDrawable#setChipIconSizeResource(@DimenRes int)`, where `@DimenRes` has retention policy `CLASS`(it's java, equals to `BINARY` in kotlin):

image

`android.app.NotificationManager#setInterruptionFilter(@InterruptionFilter int)` where `@InterruptionFilter` has retention policy `SOURCE`: 

image

> we probably shouldn't optimize for reflection use cases.

👍

**Comment by LukasPaczos** [comment]
Perfect, thanks for confirming @RingerJK! Let's use `BINARY` in this case.

**Review by LukasPaczos — APPROVED** [review]
:ship:

**Pull request merged**
