### PR TITLE
As a supplement PR to fix 2867 issue of ArrivalUiBuildingExtrusionActivityKt

### PR DESCRIPTION
**Pull request by JunDai**
## Description

This PR fix part of issue #2867 against `ArrivalUiBuildingExtrusionActivityKt` example. Since this example uses `NavigationMapRoute` to draw the route while others are using `NavigationMapboxMap`. So not sure whether it is intentional.

With this PR
* will update the puck once the navigation starts.
* will reset the puck and remove the route line on map when user ends navigation from the Notification.

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Please describe the PR goals. Just the stuff needed to implement the fix / feature and a simple rationale. It could contain many check points if needed

### Implementation

Please include all the relevant things implemented and also rationale, clarifications / disclaimers etc. related to the approach used. It could be as self code companion comments

## Screenshots or Gifs

Please include all the media files to give some context about what's being implemented or fixed. It's not mandatory to upload screenshots or gifs, but for most of the cases it becomes really handy to get into the scope of the feature / bug being fixed and also it's REALLY useful for UI related PRs screenshot gif

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by JunDai** [comment]
@langsmith - can you please review this one. Let me know if I break anything that you were trying to demonstrate in this PR. Thanks.

**Comment by langsmith** [comment]
Thanks for this @JunDai . If you don't mind, let's merge https://github.com/mapbox/mapbox-navigation-android/pull/2897 into `master` and then re-base this pr?

**Comment by JunDai** [comment]
will hold this PR until #2884 merge.

**Comment by langsmith** [comment]
> will hold this PR until #2884 merge.

Yea, sorry. I linked to the wrong pr in my comment at https://github.com/mapbox/mapbox-navigation-android/pull/2892#issuecomment-623531729. Meant to say #2884.

**Comment by JunDai** [comment]
with fix from #2932 , this issue can be closed.

**Pull request closed without merging**
