### PR TITLE
Fix #3029: update feedback bottom sheet layout so it can be used in landscape mode

### LINKED ISSUE #3029: 2TAP feedback fragment is clipped in landscape
The feedback fragment is clipped at the bottom in the landscape mode on the Pixel 2 XL.
device-2020-05-25-202522
device-2020-05-25-202543

/cc @JunDai

### PR DESCRIPTION
**Pull request by JunDai**
## Description

Fix #3029 

UX team has a design for feedback ui landscape mode but it's quite different than what we have implemented.
To resolve #3029, this PR is a temporary fix so the feedback ui can be used in landscape mode.

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

### Goal

To make Feedback flow UI available in landscape mode.

### Implementation

Add a landscape mode layout for FeedbackBottomSheet view.

## Screenshots or Gifs

ezgif com-video-to-gif (2)

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by JunDai** [comment]
> How did we test this? Should we remove the `portrait` from the `AndroidManifest`? Most of the examples have it forced e.g.
> 
> https://github.com/mapbox/mapbox-navigation-android/blob/33e41df2cd8517c9963edc3573ce25e5c374544c/examples/src/main/AndroidManifest.xml#L52
> 
> Refs. #3060

@Guardiola31337 : I remove the `portrait` restrictions locally to test the landscape mode.

**Comment by Guardiola31337** [comment]
> I remove the portrait restrictions locally to test the landscape mode.

Let's keep that change so we can easily test in the future :rocket: What do you think @JunDai?

**Comment by JunDai** [comment]
> > I remove the portrait restrictions locally to test the landscape mode.
> 
> Let's keep that change so we can easily test in the future 🚀 What do you think @JunDai?

sure. I can add those change in this PR as well.

**Comment by JunDai** [comment]
the change in example app's `AndroidManifest.xml` is just remove all the `portrait` restriction and then did a format.
@Guardiola31337 - for this change, I would suggest keep it in the separate commit. But feel free to ping me if we still want them in one commit.

**Pull request merged**
