### PR TITLE
Fix `CustomUIComponentStyleActivity` SummaryBottomSheet reappearance

### LINKED ISSUE #2917: Fix `CustomUIComponentStyleActivity` SummaryBottomSheet reappearance
A somewhat thin sliver of the the bottom of the `SummaryBottomSheet` is missing when the `NavigationView`'s camera is recentered during turn-by-turn navigation.

Screen Shot 2020-05-06 at 2 11 16 PM
Screen Shot 2020-05-06 at 2 11 22 PM
Screen Shot 2020-05-06 at 2 11 28 PM
Screen Shot 2020-05-06 at 2 10 59 PM

ezgif com-resize

### PR DESCRIPTION
**Pull request by JunDai**
## Description

Fix #2917 

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Implementation

Please include all the relevant things implemented and also rationale, clarifications / disclaimers etc. related to the approach used. It could be as self code companion comments

## Screenshots or Gifs

ezgif com-video-to-gif

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by langsmith** [comment]
>  langsmith removed their request for review now

Removed because I'm part of the Github nav team  https://github.com/orgs/mapbox/teams/navigation-android

**Comment by langsmith** [comment]
@JunDai ,

Wayname view appears when the following two conditions are true:

1. it's currently hidden
2. a maneuver is being made (e.g. device turns on to a new road when simulating route traversal)

Will post a GIF to show you what I'm talking about

**Comment by langsmith** [comment]
1. Long press to set a destination.
2. Press the `Start navigation` button to start navigating.
3. Move the map so that camera tracking is broken and hides the `wayNameView`.
4. See that the `wayNameView` appears when a maneuver is made.

ezgif com-resize (2)

**Comment by JunDai** [comment]
@langsmith - good catch!
Have updated the PR and fixed it.

**Pull request merged**
