### PR TITLE
Add battery event

### PR DESCRIPTION
**Pull request by Guardiola31337**
- Adds battery event
  - The event is scheduled to be queued every `1` minute between start and end session and it includes the battery percentage level

cc @akitchen @coxchapman

### CODE REVIEW

**Comment by Guardiola31337** [comment]
I've verified the events generated in Mode and the numbers look consistent. This is ready for review @danesfeder @devotaaabel

**Comment by akitchen** [comment]
@coxchapman 1 sec polling interval sounds aggressive to me -- can we verify this is the default interval we want to use?

**Comment by Guardiola31337** [comment]
> can we verify 1 minute is the interval we want to use by default?

I thought in 1 minute in the first place to account for the "shorter" sessions but yeah let me know if you think we should use any other "more optimal" value so I can adapt it before merging here (FWIW that's why I added the `DO NOT MERGE` label 😅).

**Comment by coxchapman** [comment]
Interested in the relative tradeoffs around frequency. More granular is better, and if anything, 1m seems long. What are the costs to greater frequency? Bandwidth / CPU?

**Comment by Guardiola31337** [comment]
Want to note that we're enqueuing these events so technically that could mean more bandwidth but internally the queue is only flushed when it's full (180 events) and every 3 minutes so enqueuing one more event every minute should not incur in extra requests.

I don't think CPU would be a problem here either. Obviously we're adding some extra methods to get the battery percentage level but those are not costly operations.

What I want to mention though is that the percentage level is rounded so a priori increasing the frequency won't have a big impact on the results i.e. it's unlikely that 1 battery point level changes in less than a minute. It'd be awesome to know how long it takes in average to drain 1 point level so we could get the optimal period rate but I guess that'd come after when we have data to reason.

Does that make sense?

**Comment by coxchapman** [comment]
Aha yes, great point about percentage rounding. Every 30 seconds then?

> when it's full (180 events) and every 3 minutes so enqueuing one more event every minute should not incur in extra requests.

If we're polling every minute, why do we fill up the queue with 180 requests in 3 minutes? Am I missing something, or would that suggest the 1/s rate?

**Comment by Guardiola31337** [comment]
> Every 30 seconds then?

As I said:

> What I want to mention though is that the percentage level is rounded so a priori increasing the frequency won't have a big impact on the results i.e. it's unlikely that 1 battery point level changes in less than a minute.

Meaning that we'll be getting the same data collected "twice" (i.e. won't add too much value, right?) and also increasing the chances of filling the queue up. As noted, it'd be great to analyze what's the optimal value but until we don't have numbers is hard to tell. But my guess is that if we need to change it will be to a greater value.

> If we're polling every minute, why do we fill up the queue with 180 requests in 3 minutes? Am I missing something, or would that suggest the 1/s rate?

Nah I was only pointing out that we are using a "shared" queue in which any kind of events are pushed and OP's work will be contributing adding one more event to this queue every one minute. The way that this queue works internally is as I mentioned sending the data gathered in the queue when it's full (180 events) or every 3 minutes. My point here was to show that we won't incur in extra requests if we add 1 more event to the queue every minute between the start and end of a navigation session (because we're not pushing neither that many events nor that often so that the queue needs to be flushed). Sorry if I didn't make myself clear.

Let me know if it makes sense now.

**Comment by Guardiola31337** [comment]
I've updated OP adding the `is_plugged_in` attribute to the battery event. I think we're good to merge 🚀 

cc @coxchapman @akitchen

**Comment by Guardiola31337** [comment]
Will quick test drive in staging and check that the numbers and the new changes recently added look 👌 in Mode, then we will be able to finally merge here :shipit:

**Comment by Guardiola31337** [comment]
> Will quick test drive in staging and check that the numbers and the new changes recently added look 👌 in Mode

Numbers showed up in Mode and look consistent and queryable 💪 

Merging here.

**Pull request merged**
