### PR TITLE
Added uncertain location puck drawable.

### LINKED ISSUE #4357: Maps module missing uncertain location puck
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior
The uncertain location puck drawable from v1.x is missing from v2.x.

### Expected behavior
There should be an uncertain location puck drawable available.

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Resolves #4357 by adding a drawable for an uncertain location puck.

### Changelog
```
<changelog>Added uncertain location puck drawable.</changelog>
```

### CODE REVIEW

**Comment by Guardiola31337** [comment]
CI is ❌ 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':libnavui-maps:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > 1 exception was raised by workers:
     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
     /root/code/libnavui-maps/src/main/res/drawable/******_navigation_puck_uncertain_location.xml:15: AAPT: error: resource color/raw_location_uncertain_gray (aka com.******.navigation.ui.maps:color/raw_location_uncertain_gray) not found.
```

**Review by Guardiola31337 — COMMENTED** [review]
How's this going to be used? It seems we're not using it internally anywhere. Even if we're not using it, how are we going to "advertise" it? How are we documenting these? We should probably document it somehow.

**Review by Guardiola31337 — APPROVED** [review]
Let's cut a follow up ticket to discuss https://github.com/mapbox/mapbox-navigation-android/pull/4358#pullrequestreview-650733660

**Comment by cafesilencio** [comment]
The route progress documentation page discusses this: https://docs.mapbox.com/android/navigation/guides/route-progress/.
I'm currently reviewing and updating this document. That's how I noticed the puck drawable was different.

**Pull request merged**
