### PR TITLE
reset step and leg indexes when reroute occurs

### LINKED ISSUE #48: Once off-route, we measure from the same snapped position causing an endless loop.
```
05-19 17:51:08.972 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 17.0
05-19 17:51:08.972 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 2.6673089788901962
05-19 17:51:09.912 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:51:09.912 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.120464490039302
05-19 17:51:11.899 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:51:11.899 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.1952861108700281
05-19 17:51:12.935 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:51:12.935 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.5276582018307443
05-19 17:51:14.946 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 16.0
05-19 17:51:14.947 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.2958761817742823
05-19 17:51:15.942 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 17.0
05-19 17:51:15.942 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.4639976027921042
05-19 17:51:17.951 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 17.0
05-19 17:51:17.951 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.234808416569313
05-19 17:51:18.921 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 17.0
05-19 17:51:18.921 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.6589061440476407
05-19 17:51:19.967 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 17.0
05-19 17:51:19.968 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.869655409333431
05-19 17:51:21.933 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 17.0
05-19 17:51:21.933 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 2.536247410736636
05-19 17:51:22.937 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 18.0
05-19 17:51:22.937 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.8308895608109472
05-19 17:51:24.951 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 19.0
05-19 17:51:24.952 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 0.0947097615169983
05-19 17:51:25.928 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 19.0
05-19 17:51:25.929 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.9738245111823365
05-19 17:51:27.919 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 16.0
05-19 17:51:27.920 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 20.92935250395903
05-19 17:51:28.953 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 16.0
05-19 17:51:28.953 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 3.5069682564933435
05-19 17:51:29.947 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 17.0
05-19 17:51:29.947 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 0.6968343303512787
05-19 17:51:31.956 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 16.0
05-19 17:51:31.957 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.2075432097227468
05-19 17:51:32.939 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 17.0
05-19 17:51:32.939 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 2.25326750154043
05-19 17:51:33.954 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 16.0
05-19 17:51:33.954 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 2.312485607613608
05-19 17:51:35.916 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:51:35.917 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.987098264973477
05-19 17:51:36.931 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 16.0
05-19 17:51:36.931 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 2.500876545599369
05-19 17:51:38.958 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:51:38.959 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.5835084095561727
05-19 17:51:39.955 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:51:39.956 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 0.8516772133033655
05-19 17:51:41.913 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:51:41.913 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 0.2026728075728913
05-19 17:51:44.943 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 13.0
05-19 17:51:44.943 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.0697906741340788
05-19 17:51:51.925 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:51:51.926 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 2.1633341236735872
05-19 17:51:53.923 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:51:53.923 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.2343921140133707
05-19 17:51:54.936 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:51:54.936 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 2.027983113197057
05-19 17:51:56.927 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:51:56.927 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 1.131519942450051
05-19 17:51:57.950 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:51:57.951 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 2.4655416279968385
05-19 17:51:59.933 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:51:59.934 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 20.048194106846864
05-19 17:52:00.940 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:52:00.941 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 28.4654527885577
05-19 17:52:01.928 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:52:01.929 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 35.45609534346335
05-19 17:52:02.929 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:52:02.929 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 41.77779286188603
05-19 17:52:04.900 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:52:04.900 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 53.97655449822273
05-19 17:52:05.915 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:52:05.916 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 58.65807539566811
05-19 17:52:06.907 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:52:06.907 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 64.57468121131893
05-19 17:52:07.911 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:52:07.911 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 71.80579155317197
05-19 17:52:08.913 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:52:08.913 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 80.0539120875666
05-19 17:52:09.912 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 14.0
05-19 17:52:09.913 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 88.99351645981768
05-19 17:52:10.923 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:52:10.923 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 97.53616789572308
05-19 17:52:12.933 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:52:12.933 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 115.82413171385913
05-19 17:52:13.929 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 15.0
05-19 17:52:13.929 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 127.29867994638687
05-19 17:52:15.905 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: radius: 16.0
05-19 17:52:15.906 5159-5159/com.mapbox.services.android.navigation.testapp I/System.out: true position: 148.64584220141234
```

### PR DESCRIPTION
**Pull request by cammace**
Closes #48 

rerouting wouldn't reset the index counts which caused off-route to measure the distance to the wrong step.

### CODE REVIEW

**Comment by Grsmto** [comment]
Hey @cammace !
Since this has been merged, it seems like the `userOffRoute` callback is called falsely. Wondering if you're aware of this or not!
`RouteUtils.isOffRoute()` is returning `false` but still, callback is triggered.
Also it's called multiple times in a short interval (which from what I read in the code shouldn't happen). I can't figure out why.
I can open an issue/provide more details if needed.

**Comment by cammace** [comment]
Hey there @Grsmto, thanks for reporting this. To clarify, you're using the SNAPSHOT build or master? I've actually been removing the `RouteUtils` methods from the nav SDK and instead directly adding the logic. 

How exactly is the `MockLocationEngine` being used? Unless you are forcing it to go off-route, the callback should never be invoked.

**Comment by Grsmto** [comment]
Hey! I'm using the SNAPSHOT build afaik (`com.mapbox.mapboxsdk:mapbox-android-navigation:0.3.0-SNAPSHOT`) and I checked I think I have the changes of this PR in my code.
About my usage of `MockLocationEngine` I basically followed the implementation of the `NavigationActivity.java` of the repo (https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/NavigationActivity.java). It even happens when I disable noise. I'll try to dig more into it maybe it's my implementations that is wrong. But I had the feeling that this happened "suddenly" without code changes, which made me think a dependency had changed (and I saw this PR and some code related hence my deduction, couldn't figure out deeper).
I'll try to isolate the bug to make sure it's not my implementation.
Thanks!

**Comment by Grsmto** [comment]
Hi @cammace !
I setup a test as promised on my fork: https://github.com/Grsmto/mapbox-navigation-android/tree/offroute-bug-test
I actually figured out that the `NavigationActivity` was missing the `navigation.addOffRouteListener()` that's probably why you didn't figure out it was happening :)
I also added a `navigation.setSnapToRoute(true);` test case as well, cause it seems like it's not working neither.
Hope this help, thanks!

**Comment by cammace** [comment]
I'll take a look at your test. I haven't been testing offroute with the `NavigationActivity` but rather the [`RerouteActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/RerouteActivity.java) which seems to be working fine on my end. By default, snapping is set to true but you have to use the location object the callbacks provide to get the snapped location, otherwise, it won't work.

**Comment by cammace** [comment]
I have fixed the index issue in https://github.com/mapbox/mapbox-navigation-android/pull/56, thanks for reporting and providing a sample to reproduce. The reason snapping to the route isn't working is actually shown in your example, only the location object provided inside OnProgress and AlertLevel are the snapped positions. The Map SDK still gets the true user location. The location plugin in https://github.com/mapbox/mapbox-plugins-android/pull/22 will fix this :)

If you are still running into issues, could you open a ticket so I can look further into it?

**Comment by Grsmto** [comment]
Hi, awesome!
About the snapped position, I'm not sure cause I did use the provided location object from `OnProgress`as you can see on [this line](https://github.com/Grsmto/mapbox-navigation-android/commit/b6d71aac24ce29f44af9f1bf863c66b78adce88d#diff-1475a4ef4a3fee9c37ed4537424b7393R225).
I'll try again and open a separate issue if I keep having the issue.

**Pull request merged**
