### PR TITLE
MapboxRouteOptionsUpdater: fix Bearings combining

### LINKED ISSUE #3888: IndexOutOfBoundsException when rerouting
**Mapbox Navigation SDK version:** `1.4.0-beta.1`

An exception caught by a crashlytics service, stacktrace:
```
Fatal Exception: java.lang.IndexOutOfBoundsException: toIndex = 3
       at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
       at java.util.ArrayList.subList(ArrayList.java:1008)
       at com.mapbox.navigation.core.routeoptions.MapboxRouteOptionsUpdater.update(MapboxRouteOptionsUpdater.java:65)
       at com.mapbox.navigation.core.reroute.MapboxRerouteController.reroute(MapboxRerouteController.java:50)
       at com.mapbox.navigation.core.MapboxNavigation.reroute(MapboxNavigation.java:746)
       at com.mapbox.navigation.core.MapboxNavigation.access$paramsProvider(MapboxNavigation.java:131)
       at com.mapbox.navigation.core.MapboxNavigation$createInternalOffRouteObserver$1.onOffRouteStateChanged(MapboxNavigation.java:740)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.setOffRoute(MapboxTripSession.java:123)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$setUNCONDITIONAL_STATUS_POLLING_INTERVAL$cp(MapboxTripSession.java:48)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.java:514)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

Might be related to https://github.com/mapbox/mapbox-navigation-android/pull/3581.

/cc @Lebedinsky @RingerJK @Guardiola31337

### PR DESCRIPTION
**Pull request by RingerJK**
### Description
MapboxRouteOptionsUpdater: fix Bearings combining

Closes #3888 

### Changelog

```
<changelog>Fixed MapboxRouteOptionsUpdater: IndexOutOfBoundsException with 'bearings' combining</changelog>
```

### CODE REVIEW

**Review by Guardiola31337 — COMMENTED** [review]
Do we have tests covering `getUpdatedBearingList` logic?

**Comment by RingerJK** [comment]
> Do we have tests covering getUpdatedBearingList logic?

https://github.com/mapbox/mapbox-navigation-android/blob/b6c86eaf47a8adad522ace86622b880d4f5dbc48/libnavigation-core/src/test/java/com/mapbox/navigation/core/routeoptions/MapboxRouteOptionsUpdaterTest.kt#L41-L90

**Comment by LukasPaczos** [comment]
@RingerJK the PR doesn't include a regression test for the issue that it's trying to fix, could you add one?

**Comment by RingerJK** [comment]
> @RingerJK the PR doesn't include a regression test for the issue that it's trying to fix, could you add one?

made a bit refactored and added one more case to tests

**Review by LukasPaczos — APPROVED** [review]
lgtm

**Review by Guardiola31337 — APPROVED** [review]

**Pull request merged**
