### PR TITLE
add nearby coords to RouteProgress

### PR DESCRIPTION
**Pull request by cammace**

### CODE REVIEW

**Comment by cammace** [comment]
@danesfeder this PRs ready for a review @danesfeder whenever you get a chance.

**Comment by cammace** [comment]
@danesfeder do we want to wait to merge this in 8.0 or can we move forward with this?

**Comment by danesfeder** [comment]
@cammace Yeah let's hold for the `0.8.0` so we have more time to test this if that's okay

**Comment by cammace** [comment]
Going to try reviewing this PR this week and seeing what is still applicable and resolve the merge conflicts in a hope to get this either merged or closed. One thing I remember fixing in this PR was issue #304

**Comment by danesfeder** [comment]
@cammace I think decoding the current / upcoming step points and passing them in the route progress adds a lot of value / makes it easier to calculate off route / snap to route.  I'm going to work on cleaning this up cc @Guardiola31337 @devotaaabel

**Comment by danesfeder** [comment]
Closing as this PR has diverged too far from `master` to save.  Using the same mindset for #812.  Thanks @cammace

**Pull request closed without merging**
