### PR TITLE
Add method to cancel all MapboxRouteLineApi tasks

### PR DESCRIPTION
**Pull request by zeac**
### Description
`MapboxRouteLineApi` is leaking consumers and so needs ability to cancel running tasks.

### Changelog
```
<changelog>Add `MapboxRouteLineApi.cancel()` to cancel running tasks</changelog>
```

### CODE REVIEW

**Comment by Guardiola31337** [comment]
Thanks for the contribution @zeac 

Noting that Metalava is failing 👀 

```
src/main/java/com/******/navigation/ui/maps/route/line/api/MapboxRouteLineApi.kt:656: error: Added method com.******.navigation.ui.maps.route.line.api.MapboxRouteLineApi.cancel() [AddedMethod]
Aborting: Found compatibility problems checking the public API (/root/code/libnavui-maps/src/main/java) against the API in /root/code/libnavui-maps/api/current.txt

> Task :libnavui-maps:checkApi FAILED
```

See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs.

@cafesilencio could you take a look at this PR when you have a chance? 🙏

**Comment by cafesilencio** [comment]
@zeac Can you provide a real world use case for this? It would help in testing to make sure it works as intended and doesn't create any side effects.

**Comment by zeac** [comment]
> @zeac Can you provide a real world use case for this? It would help in testing to make sure it works as intended and doesn't create any side effects.

You can look into `MapboxRouteLineActivity` from `qa-test-app` for instance. Currently an activity is leaking through consumers passed into `MapboxRouteLineApi`.

I added `cancel` calls to all `MapboxRouteLineApi` in this project and wonder if it is better to provide `MapboxRouteLineApi` with a parent `Job`.

**Comment by cafesilencio** [comment]
Using the profiler and leak canary I can't reproduce any leaks with the activity you mentioned or any other.  Can you provide some instructions for reproducing a leak? How did you determine a leak was occurring?

**Comment by zeac** [comment]
> Using the profiler and leak canary I can't reproduce any leaks with the activity you mentioned or any other. Can you provide some instructions for reproducing a leak? How did you determine a leak was occurring?

Here is the LeakCanary report that i got on sample app:
```
                         D  ┬───
                         D  │ GC Root: Input or output parameters in native code
                         D  │
                         D  ├─ android.os.MessageQueue instance
                         D  │    Leaking: NO (MessageQueue#mQuitting is false)
                         D  │    ↓ MessageQueue.mMessages
                         D  │                   ~~~~~~~~~
                         D  ├─ android.os.Message instance
                         D  │    Leaking: UNKNOWN
                         D  │    ↓ Message.callback
                         D  │              ~~~~~~~~
                         D  ├─ kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1 instance
                         D  │    Leaking: UNKNOWN
                         D  │    Anonymous class implementing java.lang.Runnable
                         D  │    ↓ HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.$continuation$inlined
                         D  │                                                                  ~~~~~~~~~~~~~~~~~~~~~
                         D  ├─ kotlinx.coroutines.CancellableContinuationImpl instance
                         D  │    Leaking: UNKNOWN
                         D  │    ↓ CancellableContinuationImpl.delegate
                         D  │                                  ~~~~~~~~
                         D  ├─ kotlinx.coroutines.internal.DispatchedContinuation instance
                         D  │    Leaking: UNKNOWN
                         D  │    ↓ DispatchedContinuation.continuation
                         D  │                             ~~~~~~~~~~~~
                         D  ├─ com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi$setRoutes$1 instance
                         D  │    Leaking: UNKNOWN
                         D  │    Anonymous subclass of kotlin.coroutines.jvm.internal.SuspendLambda
                         D  │    ↓ MapboxRouteLineApi$setRoutes$1.$consumer
                         D  │                                     ~~~~~~~~~
                         D  ├─ com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineApiExtensions$setRoutes$2$1 instance
                         D  │    Leaking: UNKNOWN
                         D  │    Anonymous class implementing com.mapbox.navigation.ui.base.util.MapboxNavigationConsumer
                         D  │    ↓ MapboxRouteLineApiExtensions$setRoutes$2$1.$continuation
                         D  │                                                 ~~~~~~~~~~~~~
                         D  ├─ kotlin.coroutines.SafeContinuation instance
                         D  │    Leaking: UNKNOWN
                         D  │    ↓ SafeContinuation.delegate
                         D  │                       ~~~~~~~~
                         D  ├─ kotlinx.coroutines.internal.DispatchedContinuation instance
                         D  │    Leaking: UNKNOWN
                         D  │    ↓ DispatchedContinuation.continuation
                         D  │                             ~~~~~~~~~~~~
                         D  ├─ com.mapbox.navigation.qa_test_app.view.util.RouteDrawingActivity$routeRequestCallback$1$onRoutesReady$1 instance
                         D  │    Leaking: UNKNOWN
                         D  │    Anonymous subclass of kotlin.coroutines.jvm.internal.SuspendLambda
                         D  │    ↓ RouteDrawingActivity$routeRequestCallback$1$onRoutesReady$1.this$0
                         D  │                                                                  ~~~~~~
                         D  ╰→ com.mapbox.navigation.qa_test_app.view.util.RouteDrawingActivity instance
                         D  ​     Leaking: YES (ObjectWatcher was watching this because com.mapbox.navigation.qa_test_app.view.util.RouteDrawingActivity received Activity#onDestroy() callback and Activity#mDestr
                            oyed is true)
                         D  ​     key = d8e872f3-ca1d-4ab6-83fb-c7d45ac39ace
                         D  ​     watchDurationMillis = 5188
                         D  ​     retainedDurationMillis = 148
                         D  ====================================
```

I just simulated long calculation of a route line calculation with additional `delay()`.

**Comment by zeac** [comment]
Oh, there are also MapboxRouteLineApiExtensions fixes required.

**Comment by cafesilencio** [comment]
The coroutine job in `MapboxRouteLineApi` is derived from the `ThreadController` class. When `MapboxNavigation.onDestroy()` is called it will call cancel on `ThreadController`, cancelling all child coroutines. Adding a cancel method in `MapboxRouteLineApi` would appear to be redundant.  

We haven't gotten reports of leaks from 1Tap usage or from any customers and the coroutine related code in `MapboxRouteLineApi` has been in place for some time now. I'd like to understand what circumstances might be leading to a leak you're observing.

I've been testing with long routes and haven't observed any leaks thus far. Can you describe the steps you're taking to produce a leak? Is a leak occurring through normal usage or are you having to artificially create a leak with this delay you mentioned previously?

**Comment by LukasPaczos** [comment]
> The coroutine job in MapboxRouteLineApi is derived from the ThreadController class. When MapboxNavigation.onDestroy() is called it will call cancel on ThreadController, cancelling all child coroutines. Adding a cancel method in MapboxRouteLineApi would appear to be redundant.

I would also love to hear more about a setup, but just thinking higher-level, the `MapboxNavigation` object can potentially outlive the `MapboxRouteLineApi` so maybe a cancellation method is not a bad idea.

We also seem to have more problems in the `ThreadController` - the `ThreadController#init` is only called in the `MapboxNavigation` constructor and overrides supervisor jobs. So if `MapboxRouteLineApi` is created before `MapboxNavigation`, the `MapboxNavigation#onDestroy` would not cancel `MapboxRouteLineApi` jobs and they could leak.

**Comment by LukasPaczos** [comment]
We can discuss the general `ThreadController` setup in https://github.com/mapbox/mapbox-navigation-android/issues/4853.

**Comment by cafesilencio** [comment]
If we add a cancel method in the route line api class we need to be able to explain when it needs to be called and when not to the public.  So maybe this should be better abstracted than an explicit cancel method.

**Comment by zeac** [comment]
> If we add a cancel method in the route line api class we need to be able to explain when it needs to be called and when not to the public. So maybe this should be better abstracted than an explicit cancel method.

I would say that it is expected to have `cancel` method if there are methods that take callbacks.

> I would also love to hear more about a setup, but just thinking higher-level, the `MapboxNavigation` object can potentially outlive the `MapboxRouteLineApi` so maybe a cancellation method is not a bad idea.

`MapboxRouteLineApi` seems like an object bound to `MapView` instance (via `updateTraveledRouteLine` method). So there are can be multiple `MapboxRouteLineApi` instances and their life is shorter than `MapboxNavigation`.

**Comment by cafesilencio** [comment]
The cancel capability was added via [this PR](https://github.com/mapbox/mapbox-navigation-android/pull/4911). It addresses a larger issue identified in [this issue](https://github.com/mapbox/mapbox-navigation-android/pull/4911). Closing this PR since it overlaps with the work already merged.  Thank you for this contribution.

**Pull request closed without merging**
