### PR TITLE
fix MapboxRouteLineUtilsTest

### PR DESCRIPTION
**Pull request by dzinad**

### CODE REVIEW

**Comment by cafesilencio** [comment]
Did you try something like clearing the mocks to see if it would be enough to resolve this?
```
@AfterEach 
fun tearDown() {
     clearAllMocks()
}
```

**Comment by dzinad** [comment]
> Did you try something like clearing the mocks to see if it would be enough to resolve this?

Nope, but I didn't really get the initial idea. You were trying to mock the behaviour of real objects, right? 
I mean:
`every { directionsRoute.legs() } returns route.directionsRoute.legs()` - returns list of real legs
`every { directionsRoute.legs()!!.size } returns route.directionsRoute.legs()!!.size` - mocks the behaviour of real list?
Is this even legal?

**Comment by cafesilencio** [comment]
I didn't have time to look into the issue deeply but I think there's a common mocked route, unless I'm thinking of a different test class. I thought that clearing the mocks might work as a simple fix.

**Review by cafesilencio — APPROVED** [review]

**Comment by dzinad** [comment]
The route is not mocked. It's parsed from a json. Only the native route is mocked here.

**Pull request merged**
