### PR TITLE
Bump NN dependency version to 14.1.6

### PR DESCRIPTION
**Pull request by Guardiola31337**
## Description

Bumps `mapbox-navigation-native` version to ~`14.1.4`~ `14.1.6`

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Getting the latest version from `mapboxNavigator` including the new features and bug fixes.

### Implementation

- Bump the `mapboxNavigator` version to ~`14.1.4`~ `14.1.6` in `dependencies.gradle` and fix breaking changes

## Testing

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [x] New and existing unit tests pass locally with my changes

**EDIT** Confirming that `14.1.6` solves 👇 issues 🎉 

While testing run into the following crashes 👀 

As soon as you start a _Free Drive_ session 💥 cc @LukasPaczos 

```
07-06 12:56:46.892 22109-22109/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 22109
    java.lang.IllegalArgumentException: latitude must be between -90 and 90
        at com.mapbox.mapboxsdk.geometry.LatLng.setLatitude(LatLng.java:132)
        at com.mapbox.mapboxsdk.geometry.LatLng.<init>(LatLng.java:79)
        at com.mapbox.mapboxsdk.geometry.LatLng.<init>(LatLng.java:90)
        at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.getLatLngValues(LocationAnimatorCoordinator.java:274)
        at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.feedNewLocation(LocationAnimatorCoordinator.java:110)
        at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1438)
        at com.mapbox.mapboxsdk.location.LocationComponent.forceLocationUpdate(LocationComponent.java:933)
        at com.mapbox.navigation.ui.map.NavigationMapboxMap.updateLocation(NavigationMapboxMap.java:288)
        at com.mapbox.navigation.ui.map.NavigationMapboxMap$1.onEnhancedLocationChanged(NavigationMapboxMap.java:993)
        at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession.updateEnhancedLocation(MapboxTripSession.kt:441)
        at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession.access$updateEnhancedLocation(MapboxTripSession.kt:61)
        at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$1$1.invokeSuspend(MapboxTripSession.kt:426)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

NN 💥 cc @SiarheiFedartsou @mskurydin 

```
07-06 12:34:36.216 3925-3945/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: FinalizerWatchdogDaemon
    Process: com.mapbox.navigation.examples, PID: 3925
    java.util.concurrent.TimeoutException: com.mapbox.navigator.Navigator.finalize() timed out after 10 seconds
        at com.mapbox.navigator.Navigator.finalize(Native Method)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
        at java.lang.Thread.run(Thread.java:818)
```

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

cc @mskurydin @SiarheiFedartsou @LukasPaczos

### CODE REVIEW

**Comment by Guardiola31337** [comment]
> As soon as you start a _Free Drive_ session 💥 cc @LukasPaczos 
>
>```
>07-06 12:56:46.892 22109-22109/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
>    Process: com.mapbox.navigation.examples, PID: 22109
>    java.lang.IllegalArgumentException: latitude must be between -90 and 90
>        at com.mapbox.mapboxsdk.geometry.LatLng.setLatitude(LatLng.java:132)
>        at com.mapbox.mapboxsdk.geometry.LatLng.<init>(LatLng.java:79)
>        at com.mapbox.mapboxsdk.geometry.LatLng.<init>(LatLng.java:90)
>        at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.getLatLngValues(LocationAnimatorCoordinator.java:274)
>        at com.mapbox.mapboxsdk.location.LocationAnimatorCoordinator.feedNewLocation(LocationAnimatorCoordinator.java:110)
>        at com.mapbox.mapboxsdk.location.LocationComponent.updateLocation(LocationComponent.java:1438)
>        at com.mapbox.mapboxsdk.location.LocationComponent.forceLocationUpdate(LocationComponent.java:933)
>        at com.mapbox.navigation.ui.map.NavigationMapboxMap.updateLocation(NavigationMapboxMap.java:288)
>        at com.mapbox.navigation.ui.map.NavigationMapboxMap$1.onEnhancedLocationChanged(NavigationMapboxMap.java:993)
>        at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession.updateEnhancedLocation(MapboxTripSession.kt:441)
>        at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession.access$updateEnhancedLocation(MapboxTripSession.kt:61)
>        at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$1$1.invokeSuspend(MapboxTripSession.kt:426)
>        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
>        at android.os.Handler.handleCallback(Handler.java:739)
>        at android.os.Handler.dispatchMessage(Handler.java:95)
>        at android.os.Looper.loop(Looper.java:148)
>        at android.app.ActivityThread.main(ActivityThread.java:5417)
>        at java.lang.reflect.Method.invoke(Native Method)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>```

I've debugged this and the value given to the `LocationComponent` is 👇 

```
Location[null 179769313486232000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.000000,179769313486232000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.000000 acc=0 t=?!? et=?!? alt=0.0 vel=0.0 bear=0.0]
```

cc @mskurydin @SiarheiFedartsou @LukasPaczos

**Comment by SiarheiFedartsou** [comment]
> NN 💥 cc @SiarheiFedartsou @mskurydin

@Guardiola31337 are there any steps to reproduce this issue? I've tried to open/close different activities in examples app for 10-20 times(it is how we reproduced such issues before if I am not wrong) and it didn't crash.

**Comment by Guardiola31337** [comment]
@SiarheiFedartsou 
> are there any steps to reproduce this issue? I've tried to open/close different activities in examples app for 10-20 times(it is how we reproduced such issues before if I am not wrong) and it didn't crash.

Sure thing. I recorded a quick video reproducing the crash 👀 

examples_test_app_timeout_nav_native_crash

cc @mskurydin

**Comment by Guardiola31337** [comment]
> I've debugged this 

```
[ routeState: INVALID, location: [ coordinate: Point{type=Point, bbox=null, coordinates=[-77.1692475, 39.1162307]}, time: Tue Jul 07 09:53:18 EDT 2020, speed: , bearing: , altitude: 121.6, accuracyHorizontal: 19.941, provider: fused, bearingAccuracy: , speedAccuracy: , verticalAccuracy:  ], routeIndex: 0, legIndex: 0, remainingLegDistance: 0.0, remainingLegDuration: 0, stepIndex: 0, remainingStepDistance: 0.0, remainingStepDuration: 0, stateMessage: source: fallback, inTunnel: false, predicted: 0, shapeIndex: 0, intersectionIndex: 0, roadName: , voiceInstruction: , bannerInstruction: , electronicHorizon: [ horizon: , routeIndex: 0, legIndex: 0, remainingLegDistance: 3.4028235E38, remainingLegDuration: 0, stepIndex: 0, remainingStepDistance: 3.4028235E38, remainingStepDuration: 0, shapeIndex: -1, intersectionIndex: 0 ], key_points: [ [ coordinate: Point{type=Point, bbox=null, coordinates=[1.7976931348623157E308, 1.7976931348623157E308]}, time: Wed Dec 31 19:00:00 EST 1969, speed: , bearing: 0.0, altitude: , accuracyHorizontal: , provider: , bearingAccuracy: , speedAccuracy: , verticalAccuracy:  ] ], map_matcher_output: [ matches: [  ], isTeleport: false ], offRoadProba: 0.0 ]
```

Problem is that we're getting `status.keyPoints` and it's an invalid update 👀 

examples_test_app_free_drive_key_points_invalid_14_1_4

cc @SiarheiFedartsou @mskurydin

**Comment by Guardiola31337** [comment]
> Problem is that we're getting `status.keyPoints` and it's an invalid update 👀 

```
[ coordinate: Point{type=Point, bbox=null, coordinates=[1.7976931348623157E308, 1.7976931348623157E308]}, time: Wed Dec 31 19:00:00 EST 1969, speed: , bearing: 0.0, altitude: , accuracyHorizontal: , provider: , bearingAccuracy: , speedAccuracy: , verticalAccuracy:  ]
```

**Comment by Guardiola31337** [comment]
Attaching history trace before the crash 👀 

```
{"events":[{"type":"updateLocation","location":{"lat":39.1161504,"lon":-77.1691294,"time":1594131192.376,"altitude":121.5999984741211,"accuracyHorizontal":25.38800048828125,"provider":"fused"},"result":true,"event_timestamp":1594131192.385303,"delta_ms":6},{"type":"updateLocation","location":{"lat":39.1161504,"lon":-77.1691294,"time":1594131192.368,"altitude":121.5999984741211,"accuracyHorizontal":25.38800048828125,"provider":"fused"},"result":true,"event_timestamp":1594131192.387447,"delta_ms":0},{"type":"getStatus","timestamp":1594131193.476,"event_timestamp":1594131192.408893,"result":{"route_state":"invalid","location":{"lat":39.1161504,"lon":-77.1691294,"time":1594131193.476,"altitude":121.5999984741211,"accuracyHorizontal":25.38800048828125,"provider":"fused"},"route_index":0,"leg_index":0,"remaining_leg_distance":0.0,"remaining_leg_duration":0.0,"step_index":0,"remaining_step_distance":0.0,"remaining_step_duration":0.0,"state_message":"source: fallback","in_tunnel":false,"predicted":0.0,"shape_index":0,"intersection_index":0,"road_name":"","off_road_proba":0.0,"key_points":[{"lat":1.7976931348623157e308,"lon":1.7976931348623157e308,"time":0.0,"bearing":0.0}],"map_matcher_output":{"is_teleport":false,"matches":[]}},"delta_ms":6},{"type":"getStatus","timestamp":1594131193.468,"event_timestamp":1594131244.511873,"result":{"route_state":"invalid","location":{"lat":39.11605,"lon":-77.169007,"time":1594131193.468,"bearing":216.68011474609376,"altitude":121.5999984741211,"accuracyHorizontal":25.38800048828125,"provider":"fused"},"route_index":0,"leg_index":0,"remaining_leg_distance":0.0,"remaining_leg_duration":0.0,"step_index":0,"remaining_step_distance":0.0,"remaining_step_duration":0.0,"state_message":"source: main","in_tunnel":false,"predicted":0.0,"shape_index":0,"intersection_index":0,"road_name":"","off_road_proba":0.0,"key_points":[{"lat":39.11605,"lon":-77.169007,"time":1594131193.468,"bearing":216.68011474609376}],"map_matcher_output":{"is_teleport":false,"matches":[{"proba":0.9977729320526123,"edge_id":2595609034970,"percent_along":0.0},{"proba":0.0021962907630950214,"edge_id":2185070559450,"percent_along":1.0},{"proba":0.000004611259100784082,"edge_id":2185171222746,"percent_along":0.22890973091125489},{"proba":0.0000018722295180850779,"edge_id":2185204777178,"percent_along":0.0},{"proba":0.0000018722295180850779,"edge_id":2185037005018,"percent_along":1.0},{"proba":0.0000018707088429437136,"edge_id":2184969896154,"percent_along":1.0},{"proba":0.0000018707088429437136,"edge_id":2182285541594,"percent_along":1.0},{"proba":0.0000018707088429437136,"edge_id":2182386204890,"percent_along":0.7735980749130249},{"proba":0.0000018707053186517442,"edge_id":1535121211610,"percent_along":0.4185854196548462},{"proba":0.0000018707053186517442,"edge_id":2237007244913,"percent_along":1.0},{"proba":0.0000018707053186517442,"edge_id":2236571037297,"percent_along":0.2057970017194748},{"proba":0.0000018707053186517442,"edge_id":2184936341722,"percent_along":0.0},{"proba":0.0000018707053186517442,"edge_id":1535255429338,"percent_along":0.5814145803451538},{"proba":0.0000018707053186517442,"edge_id":2372533595761,"percent_along":1.0},{"proba":0.0000018707053186517442,"edge_id":1341143040218,"percent_along":0.0},{"proba":0.0000018707053186517442,"edge_id":2595508371674,"percent_along":0.0},{"proba":0.0000018707053186517442,"edge_id":2182453313754,"percent_along":1.0}]}},"delta_ms":98}],"version":"14.1.4","history_version":"1.0.0","config":{"proximity_to_route_stay_initialized_threshold":200.0,"corral_buffer":50.0,"max_history":10,"max_retro_grade_time":3,"max_retro_grade_jitter":50.0,"max_prediction":5.0,"min_near_tunnel":20.0,"min_speed_meters_per_second":5.0,"min_annotation_distance":3.0,"voice_instruction_threshold":250.0,"default_arrival_distance":5.0,"use_EKF":true,"mpp_speed_averaging_max_points":10,"mpp_match_trace_speed_multiplier":5.0,"mpp_match_trace_minimum_distance":100.0,"mpp_match_trace_maximum_distance":1500.0,"mpp_match_trace_maximum_points":20,"mpp_match_minimum_search_radius":20,"mpp_match_maximum_search_radius":100,"mpp_minimum_length":50.0,"mpp_maximum_length":3000.0,"mpp_bearing_change_minimum_speed":0.5,"mpp_max_request_time_ms":100,"eh_max_request_time_ms":100,"eh_minimum_coverage_distance":100,"eh_maximum_coverage_distance":1500,"eh_enable_real_time_info":true,"max_speed_estimator_buffer_size":3,"look_head_time_ms":0,"points_in_uncertain_state":0,"points_outside_route_before_reporting_offroute":1},"router_params":{"tiles_path":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles","threads_count":2,"endpoints_config":{"host":"https://api.mapbox.com","version":"2020_02_02-03_00_00","userAgent":"MapboxNavigationNative","navigator_version":"14.1.4"}},"custom_config":"","profile":{"platform":"android","application":"mobile"},"tiles_folder_snapshot_before":{"entries":[{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/724/159.gph.gz","filesize":8895764,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/743/450.gph.gz","filesize":2513117,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/743/451.gph.gz","filesize":5066037,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/743/452.gph.gz","filesize":4580330,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/744/891.gph.gz","filesize":1070486,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/744/890.gph.gz","filesize":2312618,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/744/892.gph.gz","filesize":2752069,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/742/011.gph.gz","filesize":10088921,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/742/010.gph.gz","filesize":6177184,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/742/012.gph.gz","filesize":6466879,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/1/046/542.gph.gz","filesize":3162947,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/1/046/543.gph.gz","filesize":4407578,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/1/046/183.gph.gz","filesize":2277433,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/1/046/182.gph.gz","filesize":4475230,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/0/002/905.gph.gz","filesize":12057538,"permissions":384}]},"sensor_binary":"","tiles_folder_snapshot_after":{"entries":[{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/724/159.gph.gz","filesize":8895764,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/743/450.gph.gz","filesize":2513117,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/743/451.gph.gz","filesize":5066037,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/743/452.gph.gz","filesize":4580330,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/744/891.gph.gz","filesize":1070486,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/744/890.gph.gz","filesize":2312618,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/744/892.gph.gz","filesize":2752069,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/742/011.gph.gz","filesize":10088921,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/742/010.gph.gz","filesize":6177184,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/2/000/742/012.gph.gz","filesize":6466879,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/1/046/542.gph.gz","filesize":3162947,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/1/046/543.gph.gz","filesize":4407578,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/1/046/183.gph.gz","filesize":2277433,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/1/046/182.gph.gz","filesize":4475230,"permissions":384},{"filepath":"/data/user/0/com.mapbox.navigation.examples/files/Offline/api.mapbox.com/2020_02_02-03_00_00/tiles/0/002/905.gph.gz","filesize":12057538,"permissions":384}]},"http_activity":{"total_events":1,"events_in_log":1,"events":[{"url":"https://api.mapbox.com/route-tiles/v1/versions?access_token=YOUR_ACCESS_TOKEN_HERE&sku=108kcc0ixl33ff905db8d9c4035b66177d96cde6f44","user_agent":"MapboxNavigationNative/14.1.4 MapboxNavigationNative","req_time":1594131184.454122,"resp_time":1594131184.732771,"latency_sec":0.27864885330200198,"http_code":200,"size":309}]}}
```

**Pull request merged**
