### PR TITLE
DropIn render route shields

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Resolves https://github.com/mapbox/navigation-sdks/issues/1508 by rendering route shields in the `ManeuverComponent`.

### CODE REVIEW

**Review by abhishek1508 — COMMENTED** [review]
This looks good to me. 

However, I am thinking why do we need to use `MapboxNavigationViewCustomizedActivity` to test shields. We can simply test it in `MapboxNavigationViewActivity`. I see you are fixing the issue with `NavigationUIBinder` which is already a separate issue. Please let's not address the fix here and use [the ticket](https://github.com/mapbox/navigation-sdks/issues/1515) thats out there. 

We also need shields in `RoadNameLabelComponent`. Can you add that as well?

@cafesilencio

**Comment by cafesilencio** [comment]
> However, I am thinking why do we need to use MapboxNavigationViewCustomizedActivity to test shields. We can simply test it in MapboxNavigationViewActivity. I see you are fixing the issue with NavigationUIBinder which is already a separate issue. Please let's not address the fix here and use https://github.com/mapbox/navigation-sdks/issues/1515 thats out there

These classes were only changed for compilation.

**Comment by cafesilencio** [comment]
> We also need shields in RoadNameLabelComponent. Can you add that as well?

I don't see a RoadNameLabelComponent anywhere.

**Comment by abhishek1508** [comment]
> > We also need shields in RoadNameLabelComponent. Can you add that as well?
> 
> I don't see a RoadNameLabelComponent anywhere.

It's `RoadNameComponent`. Let's change it to `RoadNameLabelComponent` to match the standalone UI
@cafesilencio

**Comment by cafesilencio** [comment]
> We also need shields in RoadNameLabelComponent. 

The scope of the ticket #1508 is to add shields to the maneuver component.  If there is a need to add shields in other places there should be tickets defining those tasks.

**Comment by abhishek1508** [comment]
> If there is a need to add shields in other places there should be tickets defining those tasks.

I forgot to capture `RoadNameLabel` in the description of the original ticket, but as the title of the ticket is quite generic it makes sense to me to render shields in components that need it, in this PR itself. I am okay if you want to do it in a separate ticket though 👍🏻

**Review by abhishek1508 — APPROVED** [review]

**Pull request merged**
