### PR TITLE
Introduce changes to transifex config

### PR DESCRIPTION
**Pull request by abhishek1508**
## Description

Add changes to transifex config to account for the translations that got added to `libtrip-notification`

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Add changes to transifex config to account for the translations that got added to `libtrip-notification`

### Implementation

Add changes to transifex config to account for the translations that got added to `libtrip-notification`

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by langsmith** [comment]
This pr resolves https://github.com/mapbox/mapbox-navigation-android/issues/2453

I've uploaded the https://github.com/mapbox/mapbox-navigation-android/blob/master/libtrip-notification/src/main/res/values/strings.xml file as a new resource in our Nav SDK Transifex project.

This pr is ready for another review and merge.

Screen Shot 2020-02-21 at 10 20 17 AM

Screen Shot 2020-02-21 at 10 13 19 AM

Screen Shot 2020-02-21 at 10 13 38 AM

**Comment by langsmith** [comment]
I added the `tools:ignore="MissingTranslation"` to the strings in this pr to get rid of the annoying errors being thrown by Android Studio when the strings file is being viewed.

**Comment by 1ec5** [comment]
If you haven’t already, remember to set up Transifex to automatically detect changes to the source file here on GitHub, and also click the inscrutable watch icon on the Transifex project’s dashboard so you get notified by e-mail when newly completed translations roll in.

**Comment by langsmith** [comment]
> the inscrutable watch icon on the Transifex project’s dashboard so you get notified by e-mail when newly completed translations roll in

For others following, here's where to do this.

Screen Shot 2020-02-21 at 3 01 21 PM

**Comment by langsmith** [comment]
Noting an important discovery that @Guardiola31337 and I made after **lots** of trial and error with Transifex pushing/pulling via the command line client.

`<?xml version="1.0" encoding="utf-8"?>` should be at the top of each language file in the `libtrip-notification` module. Pushing to Transifex via the command line doesn't work without this line.

**Comment by langsmith** [comment]
`tx push -t -r mapbox-navigation-sdk-for-android.libtrip-notification-strings-file` is the correct command for pushing to the `libtrip-notification` module.

**Pull request merged**
