### PR TITLE
Persist route line and building highlighting layers

### PR DESCRIPTION
**Pull request by LukasPaczos**
### Description

Uses the new persistent layers API to avoid route lines blinking on style changes.

### Changelog

```
### Feature
<changelog>Made route line, route arrow, and building highlighting layers persistent which means that they will survive style changes automatically, without needing to be manually redrawn. This also removes any sort of flickering of the route line when a map style changes.</changelog>

### Bug fix
<changelog>Fixed an issue where restricted road sections layer was not re-added to the map when drawing data if it was previously manually removed.</changelog>
```

### Screenshots or Gifs

_Before:_

https://user-images.githubusercontent.com/16925074/129359895-c7372727-8407-404b-8530-620dae1990f9.mp4

_After:_

https://user-images.githubusercontent.com/16925074/129359973-1ad88f46-aec6-4fb1-8078-67484203bf8a.mp4

### CODE REVIEW

**Comment by LukasPaczos** [comment]
Blocked by https://github.com/mapbox/mapbox-maps-android/issues/452.

**Comment by LukasPaczos** [comment]
Blocked by https://github.com/mapbox/mapbox-maps-android/issues/498.

**Comment by LukasPaczos** [comment]
This should be unblocked now with the update to Maps SDK 10.0.0-rc.6.

**Review by Guardiola31337 — APPROVED** [review]
🚀

**Comment by LukasPaczos** [comment]
Capturing from @alexshalamov, there could still be some edge cases where layers will not be ordered correctly after a style change. Those will be addressed in the next cycle of Maps SDK releases. I'm going to hold off on merging until then.

**Comment by LukasPaczos** [comment]
The abovementioned fix will be available in the Maps SDK `10.0.0-rc.9`.

**Comment by zugaldia** [comment]
Next steps is to retest now that rc.8 is out and integrated with Nav SDK https://github.com/mapbox/mapbox-maps-android/releases/tag/android-v10.0.0-rc.8

**Comment by LukasPaczos** [comment]
This change will target Nav SDK `v2.0.0-rc.3`/`v2.1.0-alpha.1`.

**Comment by LukasPaczos** [comment]
This PR is updated, adds another small fix when checking the existence of restricted layers, and adds docs. Ready for another round of reviews.

**Review by Guardiola31337 — APPROVED** [review]
LGTM :shipit:

**Pull request merged**
