### PR TITLE
Add more logs to MapboxTripSession

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**
It is needed to improve debuggability of issues.

### CODE REVIEW

**Comment by VysotskiVadim** [comment]
Can you troubleshoot the issue from your branch? Why do you need so many logs in the main branch?

**Comment by VysotskiVadim** [comment]
> Why it is a problem?

I don't think it's a problem. Having more logs is just something new for me and I guess for the whole Android team 🙂 

I would ask other members of @mapbox/navigation-android:
1. are okay with logging everything to be able to understand what when wrong on user's side? 
2. Is there any reason we haven't added logs for everything already? 
3. How would you like the logs to be structured/filtered? Current PR suggests using category which matches class name.

**Comment by SiarheiFedartsou** [comment]
>Current PR suggests using category which matches class name.

I just followed approach I've seen in other places in codebase.

**Comment by LukasPaczos** [comment]
There's a balance that we'll need to find when it comes to this type of verbose logging. I'm in generally not against adding more traces to the SDK, I think that could be extremely beneficial, but we also need to be strategic about it. Too many logs not only flood the logcat with noise, generate log files that become _huge_ and hard to work with but also make the actual code less readable. In worst cases like performance sensitive code (for example a callback that fires on each frame) having things like extensive string concatenation for logs can actually have a non-negligible impact on performance.

Let's define what information we need from a log before adding it to the production code.

@SiarheiFedartsou I pushed a commit that cleans up the proposed `MapboxTripSession` logs a bit, I know we're currently trying to debug some issues with delayed locations so I think it's fine to leave them in place at least for the duration of the exercise. Let me know if the changes work for you.

@SiarheiFedartsou why do we need logs for start/end of road objects matching? If we're planning to measure the performance, there are definitely better ways to do it than production logs.

@mapbox/navigation-android - I'm going to add a topic for our periodic sync to get a discussion going on verbose logging.

**Comment by SiarheiFedartsou** [comment]
>@SiarheiFedartsou why do we need logs for start/end of road objects matching? If we're planning to measure the performance, there are definitely better ways to do it than production logs.

Well, I was just going to use it to track if we have any delays in user-provided observers. It is not something that I think we need to have, I added it just in case - it may help at some point in the future. But I am completely okay with deleting it if you have concerns.

> @SiarheiFedartsou I pushed a commit that cleans up the proposed MapboxTripSession logs a bit, I know we're currently trying to debug some issues with delayed locations so I think it's fine to leave them in place at least for the duration of the exercise. Let me know if the changes work for you.

Looks fine 👍🏻 


My point is that this is debug logs and user should be always able to increase log level and don't see them at all(btw will it have any performance impact in this case?), but to debug complicated problems having such verbose logs is vital IMO. WDYT?

**Comment by LukasPaczos** [comment]
> user should be always able to increase log level and don't see them at all(btw will it have any performance impact in this case?)

This won't remove the processing time needed to create and dispatch the log message (granted it's typically marginal but we need to have it in mind for those critical sections).

I agree that we can add more logs, I just want us to be more intentional about it.

In this case let's merge the `MapboxTripSession` logs and remove the e-horizon ones, could you do that @SiarheiFedartsou?

**Review by LukasPaczos — APPROVED** [review]
:ship:

**Comment by Guardiola31337** [comment]
I went ahead and fixed the failing tests https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/17321/workflows/4774b502-067c-410d-981b-0c583385e008/jobs/78244 https://github.com/mapbox/mapbox-navigation-android/blob/28cfce69e3ac9a605f5739a5e5a632e69618a694/libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionNoSetupTest.kt#L50-L51 https://github.com/mapbox/mapbox-navigation-android/blob/28cfce69e3ac9a605f5739a5e5a632e69618a694/libnavigation-core/src/test/java/com/mapbox/navigation/core/trip/session/MapboxTripSessionTest.kt#L84-L85 and re-pushed. @SiarheiFedartsou feel free to merge when you have a chance 🚀

**Comment by SiarheiFedartsou** [comment]
@mapbox/navigation-android any ideas why I constantly have failures on instrumentation tests? https://app.circleci.com/jobs/github/mapbox/mapbox-navigation-android/78351?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Guardiola31337** [comment]
Nah that's unrelated, it's happening lately  https://github.com/mapbox/mapbox-navigation-android/pull/5622#issuecomment-1083676837 we should be good merging 👍

**Pull request merged**
