### PR TITLE
UX change: put the guidance view to the left of the NavigationView in landscape mode

### PR DESCRIPTION
**Pull request by JunDai**
## Description

UX refactor:
1. put the guidance view to the left of the NavigationView in landscape mode
2. change the recenter button from text to icon

- [ ] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

### Goal

Improve the GuidanceView landscape experience in NavigationView.

### Implementation

per discussion with team, we decided to:
1. use an icon for `re-center` button
2. put the `re-center` button under the Feedback button at right side of screen
3. put the GuidanceView at the most left of the screen in landscape mode, move the puck to right when GuidanceView appears

## Screenshots or Gifs
ezgif com-video-to-gif (3)

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make core-update-api` (Core) / `$> make ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs

### CODE REVIEW

**Comment by JunDai** [comment]
cc: @map-angela / @asinghal22 : please see the gif for UX, let me know if anything we should fix.

**Comment by JunDai** [comment]
@danpaz - hey, you can see the gif I attached in this PR. There is a blank area between the GuidanceImage and the top banner instruction view. That's for the sub step instruction view. But can I assume that there will not be a sub step instruction when a GuidanceImage(aka JunctionView) is displaying?

If we can confirm this, then I can remove that blank area and the UI will look much better.

**Comment by danpaz** [comment]
> @danpaz - hey, you can see the gif I attached in this PR. There is a blank area between the GuidanceImage and the top banner instruction view. That's for the sub step instruction view. But can I assume that there will not be a sub step instruction when a GuidanceImage(aka JunctionView) is displaying?
>
> If we can confirm this, then I can remove that blank area and the UI will look much better.

Hey @JunDai no, at this point it is possible to have both a `sub` and a `view` in the same banner instruction. For example the sub instruction might show information about the _next_ maneuver and the view would show information about the current maneuver. 
Is it possible to dynamically adjust the image position based on whether a sub is present or not?

**Comment by abhishek1508** [comment]
Thanks @danpaz for confirming.

@map-angela @asinghal22 
Do you folks want us to constraint the guidance view to the sub step? In that case the guidance view will constraint to the bottom of the top banner instruction when there is no sub instruction and will constraint to the bottom of sub instruction when we have one. 
**Or** 
What you see in the `gif` attached above good enough? This is what we discussed btw. But, wanted to reach out once again, now that we have a working visual to see.

cc @JunDai @Guardiola31337

**Comment by asinghal22** [comment]
@abhishek1508 Lets keep original design for now. If there is feedback from market/developers we will iterate and improve.

**Comment by JunDai** [comment]
> @abhishek1508 Lets keep original design for now. If there is feedback from market/developers we will iterate and improve.

@asinghal22 - just confirm, what the gif shows above is OK for now. We don't want to adjust the GuidanceView size runtime when the sub step shows and hides.

**Comment by asinghal22** [comment]
> > @abhishek1508 Lets keep original design for now. If there is feedback from market/developers we will iterate and improve.
> 
> @asinghal22 - just confirm, what the gif shows above is OK for now. We don't want to adjust the GuidanceView size runtime when the sub step shows and hides.

Yes. What the gif shows is OK for now.

**Comment by abhishek1508** [comment]
>@asinghal22 - just confirm, what the gif shows above is OK for now. We don't want to adjust the GuidanceView size runtime when the sub step shows and hides.

Yes the gif is fine. We just need to move the `WayNameView` and round the top left and top right corners
cc @JunDai

**Comment by JunDai** [comment]
@map-angela / @asinghal22 : can you please checkout the gif again? I updated it with two changes than the initial one:
* add an animation to move the `wayName` label, there is another puck moving animation will be integrated soon once the **map-sdk** has new version available.
* update the `GuidanceView` to have four corners rounded. two reason for this, but let me know if you all feel we should only do _top-left and top-right corners rounded_.
**a)** four corners is much easier to implement, and for same reason, the rounded corners is not available on API 19(but API 19 has really small distribution)
**b)** the SummaryBottomShee will be hidden in overview mode, so it makes sense to have the bottom corners rounded IMO


cc: @abhishek1508 / @Guardiola31337 : feel free to comment.

**Pull request merged**
