### PR TITLE
Notify InstructionListAdapter after animation finishes

### LINKED ISSUE #1137: Current instruction is not removed after completed
Noticed that the current instruction is not removed after completed in certain scenarios 👀 

instruction_not_removed

Noting that this may be related to https://github.com/mapbox/mapbox-navigation-android/issues/1136

### PR DESCRIPTION
**Pull request by danesfeder**
Fixes #1137 

Was able to reliably reproduce #1136 - looks like some sort of issue when updating the adapter with data / animation to show the list.  

This PR adjusts the adapter notification to happen before the animation begins.  @Guardiola31337 do you mind confirming this fixes on your devices as well?  Thanks!

### CODE REVIEW

**Comment by Guardiola31337** [comment]
@danesfeder 
> do you mind confirming this fixes on your devices as well? Thanks!

Unfortunately, it doesn't fix it 😭 

instruction_list_flash

**Comment by danesfeder** [comment]
@Guardiola31337 do you mind trying to reproduce with the new changes? 🙏

**Comment by Guardiola31337** [comment]
@danesfeder 
> do you mind trying to reproduce with the new changes? 🙏

Moto X (2nd gen) - Android version 5.0

list_flashing_issue_stuck_moto_x

Note that sometimes the list gets stuck and remains faded until the map animation ends.
Also if you 👀 carefully `Avinguda del Primat Reig` instruction (2nd instruction) gets resized somehow.

list_flashing_issue_moto_x

Was able to reproduce https://github.com/mapbox/mapbox-navigation-android/issues/1136 although it was harder this time.

Nexus 5 - Android version 6.0

list_flashing_issue_nexus_5

This is what I got with the Nexus 5. Note that in this case the first instruction `Carrer de Dolores Marqués` gets resized sometimes.

list_flashing_issue_smooth_nexus_5

Note that with the Nexus 5 I wasn't able to get the faded stuck behavior mentioned above and overall works smoothly.

**Comment by danesfeder** [comment]
@devotaaabel @Guardiola31337 I was able to find the issue with the list being updated and checked-in a possible fix.  If either of you get a chance to look at the outstanding animation issues, please feel free to dig.  Also, if approved, feel free to merge this PR at will.  Thanks!

**Comment by Guardiola31337** [comment]
With latest changes I wasn't able to reproduce https://github.com/mapbox/mapbox-navigation-android/issues/1136#issuecomment-411334202
> Noting that instructions are not removed after completed

nor https://github.com/mapbox/mapbox-navigation-android/issues/1137
> Noticed that the current instruction is not removed after completed in certain scenarios

nor https://github.com/mapbox/mapbox-navigation-android/pull/1143#issuecomment-410977935
> Note that sometimes the list gets stuck and remains faded until the map animation ends.

but still flashes if you click continuously on the top banner https://github.com/mapbox/mapbox-navigation-android/issues/1136 and sometimes that the text of the instructions gets resized 👀 

Moto X (2nd gen) - Android version 5.0

instructions_flash_issue_moto_x

Nexus 5 - Android version 6.0

instruction_flash_issue_nexus_5

So I'm going to edit OP to reflect that this PR actually fixes #1137 and leave #1136 opened for more investigation on how to fix the remaining animation issues.

**Pull request merged**
