### PR TITLE
Update Nav Native to v69.0.2 and extend the reroute instrumentation test

### PR DESCRIPTION
**Pull request by LukasPaczos**
### Description

Backports https://github.com/mapbox/mapbox-navigation-android/pull/4998 to the release branch which should make the instrumentation tests fail until a patch from NN is available.

### Changelog

```
<changelog>Fixed and issue where after reroute an additional waypoint was added to the new route (equal to the starting point of the original route).</changelog>
```

### CODE REVIEW

**Comment by LukasPaczos** [comment]
This did land `v2.0.0` @tkvalentine56. Would you be able to share the JSON (`DirectionsRoute#toJson`) of the route this is reproducible?

**Comment by tkvalentine56** [comment]
Yes, let me fix our code to save this value for retrieval. I will forward
the results when I retest.

**Comment by tkvalentine56** [comment]
Here is log output from a navigation run today. Notes are embedded as well as the route progress event associated route directions json.
[route_directions_log_output.txt](https://github.com/mapbox/mapbox-navigation-android/files/7455820/route_directions_log_output.txt)

**Comment by LukasPaczos** [comment]
Thanks @tkvalentine56, let's continue in https://github.com/mapbox/mapbox-navigation-android/issues/5092.

**Pull request merged**
