### PR TITLE
AlertView integrated with post-reroute feedback 

### PR DESCRIPTION
**Pull request by danesfeder**
- Create AlertView and integrate with navigation feedback
- Extract feedback logic to InstructionView

TODO:
- [x] Adjust loading `Drawable` colors

### CODE REVIEW

**Comment by danesfeder** [comment]
ezgif com-video-to-gif

**Comment by ericrwolfe** [comment]
Moar padding plz.
image

**Comment by danesfeder** [comment]
device-2017-11-07-181226

@ericrwolfe better?

**Comment by danesfeder** [comment]
ezgif com-video-to-gif

**Pull request merged**
