### PR TITLE
updated README.md

### PR DESCRIPTION
**Pull request by LukasPaczos**
### Description

Closes https://github.com/mapbox/mapbox-navigation-android/issues/5190.

I took a first stab and getting the readme up to date. @AhmerKhan1 and @colleenmcginnis I'd appreciate if you could review and provide additional content that we might want to include here.

### CODE REVIEW

**Review by colleenmcginnis — APPROVED** [review]
Looks good to me. Thanks @LukasPaczos!

**Comment by abhishek1508** [comment]
This looks good. I want to add two comments to this PR:
- What do you think about adding some screenshots of actual device showcasing navigation capabilities? Adding phone, android auto and how automotive customers are using our SDK gives a lot of credibility and gets the reader excited. 
- Even though Nav SDK Android docs mentions the current version, it's not natural for a developer to visit the documentation page to find out the current stable version. Rather, they prefer to find it out through the README of the repository. We should either add a section mentioned below
```
dependencies {
  implementation "com.mapbox.navigation:android:2.1.1"
}
```
or attach a reference to `CHANGELOG` probably that can enable the user to find out the stable release version quickly.

/cc @colleenmcginnis @LukasPaczos @AhmerKhan1

**Comment by RingerJK** [comment]
Could you also update the `Using Snapshots` section:
- https://docs.mapbox.com/android/beta/navigation/overview/#installation is broken, should be replaced by https://docs.mapbox.com/android/navigation/guides/get-started/install/#add-the-dependency
- following is not true: 
```
To access SNAPSHOT builds follow the [installation instructions](https://docs.mapbox.com/android/beta/navigation/overview/#installation) but replace the repository url and the version name:
```
If you replace **releases** _url_ by **snapshot**, releases repo become unreachable, so maps, NN, core, and other Mbx dependencies cannot be synced.
Need to be replaced by something like 
```
To access SNAPSHOT builds follow the [installation instructions](https://docs.mapbox.com/android/beta/navigation/overview/#installation) but add the snapshots repository setup additional to existing releases:
```

**Comment by LukasPaczos** [comment]
@abhishek1508 - I'd prefer keeping readme light. It's going to be better for us to a have a single source of truth in form of the docs pages, I just added a link to changelog/releases. We can consider adding more screenshots separately.

@RingerJK - fixed!

**Review by RingerJK — APPROVED** [review]
LGTM

**Pull request merged**
