### PR TITLE
Add UI's text size into attributes of NavigationView and styles.xml

### PR DESCRIPTION
**Pull request by luugiathuy**
## Description

Please include a brief summary of the change and which issue is fixed (e.g., fixes [#issue](link))

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Allowing customize text size of the TextView in NavigationView. In some cases, the NavigationView may not cover whole screen thus the default size is not suitable for it. This will allow developers to change the text size for both portrait/landscape mode.

### Implementation

Since we have layout for portrait and landscape orientations and the text size may be different for them, I have extracted the text size and put in `attrs.xml` in format `navigationView...TextSizePortrait` and `navigationView...TextSizeLandscape`. The default value of these attributes are in the `styles.xml` file.

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by luugiathuy** [comment]
@dfnerio Thanks for reviewing, how do I trigger the circleci build?

**Comment by dfnerio** [comment]
@luugiathuy I don't know, can't figure it out either 🤔

**Comment by Guardiola31337** [comment]
Is this something currently an option in `1.0`? Could you confirm @JunDai?

cc @abhishek1508

**Comment by JunDai** [comment]
no, we don't support text size customization in 1.0

**Comment by abhishek1508** [comment]
@luugiathuy Thanks for the contribution. We are under an overhaul of the UI SDK and we’ll be adding this feature as part of the next major release. I am going to close this PR for now.

**Pull request closed without merging**
