### PR TITLE
Kyv fix leak navigation map route 

### PR DESCRIPTION
**Pull request by RingerJK**
## Description

A `Fragment` leaks because of NavigationMapRoute observe `Context` lifecycle(that is an `Activity`)
Updated leak canary version to `2.3`
- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Please describe the PR goals. Just the stuff needed to implement the fix / feature and a simple rationale. It could contain many check points if needed

### Implementation

Please include all the relevant things implemented and also rationale, clarifications / disclaimers etc. related to the approach used. It could be as self code companion comments

## Screenshots or Gifs

Please include all the media files to give some context about what's being implemented or fixed. It's not mandatory to upload screenshots or gifs, but for most of the cases it becomes really handy to get into the scope of the feature / bug being fixed and also it's REALLY useful for UI related PRs screenshot gif

## Testing

Please describe the manual tests that you ran to verify your changes

- [ ] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by Guardiola31337** [comment]
Refs. https://github.com/mapbox/mapbox-navigation-android/pull/2882

**Comment by cafesilencio** [comment]
I think originally the NavigationMapRoute class was a LifecycleObserver but never registered itself with a LifeCycleOwner.  Which is perhaps why this wasn't noticed in the past.

There are a couple classes that use NavigationMapRoute but not NavigationMapboxMap like BaseRouteActivity, TripServiceActivity and perhaps others. Can those get updated in this PR as well so they don't start leaking? 

There are a lot of classes that require a developer to call onStart onStop etc. We should think about adding LifeCycleOwner to the constructor of some classes to reduce the burden on developers.

**Comment by RingerJK** [comment]
@cafesilencio we didn't notice that because our `examples` are driven by `Activities`, not `Fragments`.
Sure, I'll fix other classes, also I suggest add `Builder` to `NavigationMapRoute` because we already have **8** constructors here.  
ptal at reported issue in `1tap` repo

**Comment by RingerJK** [comment]
Converted to draft, because it's one of option, but still **ready for review**

**Comment by RingerJK** [comment]
Solution https://github.com/mapbox/mapbox-navigation-android/pull/3012 was applied

**Pull request closed without merging**
