### PR TITLE
Add jank detector user interface

### PR DESCRIPTION
**Pull request by kmadsen**
## Description

Building on top of https://github.com/mapbox/mapbox-navigation-android/pull/3320

Made a user interface for showing jank

- [ ] I have added any issue links
- [ ] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

## Screenshots or Gifs

| Some jank | Lots of jank |
| --- | --- |
| output | output |

## Testing

Please describe the manual tests that you ran to verify your changes

- [ ] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make 1.0-core-update-api` (Core) / `$> make 1.0-ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs

@Guardiola31337 @zugaldia

### CODE REVIEW

**Comment by zugaldia** [comment]
Both https://github.com/mapbox/mapbox-navigation-android/pull/3320 and this one are looking great - I'm particularly excited about the door they open for automatic metrics collection.

From a developer perspective: what would you say are the pros and cons of using this jank detector UI, versus the one provided by [Android developer options](https://developer.android.com/topic/performance/rendering/inspect-gpu-rendering#gpu_rendering_output)?

**Comment by LukasPaczos** [comment]
This looks awesome!

> I found that FrameMetrics isn't perfectly accurate - jank goes unnoticed.

When you mention that it isn't perfectly accurate, did you have a chance to compare it with the `dumpsys` commands or does it use the same exact toolchain under the hood? Also, we've discovered that the `GLSurfaceView` that the Maps SDK uses by default has a hard time give us back any meaningful frame rendering metrics. Switching to `TextureView` rendering surface was returning much more realistic results (you can do that with `MapboxMapOptions` or an XML `MapView` attribute). I can see that manipulating the map does give you back frame stats (even the built-in Android dev tool doesn't return anything for the `GLSurfaceView` impl), did you perhaps compare those 2?

**Comment by kmadsen** [comment]
> When you mention that it isn't perfectly accurate, did you have a chance to compare it with the dumpsys commands or does it use the same exact toolchain under the hood?

Yeah they appear to be the same toolchain, framemetrics are a callback from [android native sources](https://github.com/aosp-mirror/platform_frameworks_base/blob/a4ddee215e41ea232340c14ef92d6e9f290e5174/core/jni/android_view_ThreadedRenderer.cpp#L1181), and then it's sent up to the [Window observers](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/FrameMetricsObserver.java;l=71-76;bpv=1;bpt=1). I ran a sanity check with `adb shell dumpsys gfxinfo com.mapbox.navigation.examples`, and run it in parallel with an example running. Verified that the "frame" counts are identical. Also noticed that these metrics are used for [other industry benchmarks](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/tests/UiBench/src/com/android/test/uibench/RenderingJitter.java?q=FrameMetrics&ss=android%2Fplatform%2Fsuperproject).

UI metric tools will measure main thread performance. However, if there are long operations on background threads that are cause visual elements to appear janky - that will go unmeasured by these tools. I haven't proved that is the source of our unnoticed jank. Maybe need System Trace for this.

> Switching to TextureView rendering surface was returning much more realistic results (you can do that with MapboxMapOptions or an XML MapView attribute). I can see that manipulating the map does give you back frame stats (even the built-in Android dev tool doesn't return anything for the GLSurfaceView impl), did you perhaps compare those 2?

I didn't look into either of these, interesting though because the jank source seems to be coming from the map, not navigation. but I may have a leak in this jank detector 😅

**Comment by kmadsen** [comment]
Closing for now. This can be looked into when addressing these issues

https://github.com/mapbox/navigation-sdks/issues/507
https://github.com/mapbox/navigation-sdks/issues/479

**Pull request closed without merging**
