### PR TITLE
Docs v2.0.0-beta.1

### PR DESCRIPTION
**Pull request by LukasPaczos**
**Docs v2.0.0-beta.1**
        <br/>**Staging**:
        - github/publisher-staging https://github.com/mapbox/mapbox-navigation-android/tree/publisher-staging/2.0.0-beta.1
        - staging docs https://docs.tilestream.net/android/navigation/api-reference/
        - staging docs v2.0.0-beta.1 https://docs.tilestream.net/android/navigation/api/2.0.0-beta.1/-modules.html
        <br/>**cc** @mapbox/navigation-android

### CODE REVIEW

**Comment by colleenmcginnis** [comment]
@LukasPaczos it looks like you might have an extra module in there ("libnavigation-android" is empty): 

image

**Comment by colleenmcginnis** [comment]
Same as https://github.com/mapbox/mapbox-navigation-android/pull/4118#issuecomment-795616280 🙂

**Comment by RingerJK** [comment]
@colleenmcginnis could you have a look at why staging docs aren't presented?
`2.0.0-beta.1` for staging is merged https://github.com/mapbox/mapbox-navigation-android/tree/publisher-staging/2.0.0-beta.1, but the link https://docs.tilestream.net/android/navigation/api/2.0.0-beta.1/-modules.html is broken

**Comment by RingerJK** [comment]
> https://docs.tilestream.net/android/navigation/api/2.0.0-beta.1/-modules.html

@colleenmcginnis staging docs are still not running, is it the right link?

**Comment by colleenmcginnis** [comment]
@RingerJK we're seeing this issue for most PRs adding Dokka docs (see https://github.com/mapbox/mapbox-maps-android/pull/223). Sometimes when the diff is too big (these Dokka PRs have a couple thousand files), our publishing system is not triggered. @danswick is going to reach out to the release engineering team this week to see if there's a fix. In the meantime, you can trigger the build with an empty commit like I did in https://github.com/mapbox/mapbox-navigation-android/commit/442b714250aaf6df87a206afecab978e2dccab77.

**Pull request merged**
