### PR TITLE
Add NavigationView#retrieveSpeechPlayer for playing speech announcements

### LINKED ISSUE #1147: Allow usage of NavigationView speech apis for custom announcements
Currently developers have no way of accessing the internal `NavigationSpeechPlayer` we use to voice our speech instructions. 

 Using a separate speech API of their own (like their own instance of `TextToSpeech`) would create a fractured voice experience for the end-user and doesn't allow queueing within our own speech announcements (possibility of overlapping announcements).

Adding an API like `NavigationView#retrieveSpeechPlayer` would allow developers to access our default `NavigationSpeechPlayer`, or in the future, possibly a shared custom implementation (see #1146).

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #1147 

This PR allows access to the `NavigationViewModel` `SpeechPlayer`.  By default we create `NavigationSpeechPlayer` which will be provided here.  In the future, we will allow custom `SpeechPlayer` implementations which, when provided, will be passed via this method instead.  

TODO: 
- [x] Javadoc 
- [x] Test

### CODE REVIEW

**Comment by Guardiola31337** [comment]
@danesfeder and I had a great discussion about:

_Should we expose `NavigationView#retrieveSpeechPlayer` if the same functionality could be achieved with other available APIs?_

The point here is that when https://github.com/mapbox/mapbox-navigation-android/pull/1232 lands clients will be able to provide custom `SpeechPlayer` implementations making this new API "obsolete" / not needed.

#1232 will offer the following usages to clients:
- default 👉 don't need to do anything (managed by the SDK, `NavigationSpeechPlayer` is used)
- custom 👉 provide your own `SpeechPlayer` implementation via `NavigationViewOptions`
- custom default 👉 use `NavigationSpeechPlayer` (which is already `public`) and pass it as "custom" NavigationViewOption (if needed)

Noting that `retrieveMapboxNavigationSpeechPlayer` (OP) was a customer request and custom `SpeechPlayer` (#1232) is iOS parity.

So, why would we need to support / offer both?

IMO, this is something that we need to consider constantly when adding / exposing a new API. Offering different ways with which you could get the same, could be confusing to clients (behavior duplication) + also would mean more APIs to maintain from our side.

---

> Build APIs that will be fondly remembered.

https://twitter.com/Piwai/status/1007267211520557057

> Intuitive APIs feel intuitive to you because:
>
> a) you have a good conceptual model in mind
> b) They're designed with constraints that make you do the right thing without thinking, e.g. cultural constraints (code conventions) and physical constraints (compiler / autocomplete)

https://twitter.com/Piwai/status/1007297948697284608

By @pyricau

> There’s a saying that I like: an API is like a baby. They’re fun to make, but they take 18 years to support. Any API we add is going to have to be supported for a long time so we want the confidence that we’re building it the right way.

https://academy.realm.io/posts/oredev-ty-smith-building-android-sdks-fabric/

By @tyvsmith

---

What do you think @mapbox/navigation-android @akitchen? I'd love to hear your thoughts on this 🙏 

cc'ing @taraniduncan to know your thoughts too on the "product" side of things of this discussion.

**Comment by tyvsmith** [comment]
Having multiple ways to do something can cause confusion and leave you with tech debt, probably want to keep it as simple as possible and hold off on this one. If y'all are prioritizing the approach in #1232, I'd hold off here.

**Comment by Guardiola31337** [comment]
Hey @tyvsmith 👋 thanks for jumping in here and share your thoughts! Really appreciate them 🙏

**Comment by danesfeder** [comment]
Closing in favor of https://github.com/mapbox/mapbox-navigation-android/pull/1232.  Thanks for input here @Guardiola31337 @tyvsmith

**Pull request closed without merging**
