### PR TITLE
Docs v2.0.0-beta.4

### PR DESCRIPTION
**Pull request by korshaknn**
**Docs v2.0.0-beta.4**
        <br/>**Staging**:
        - github/publisher-staging https://github.com/mapbox/mapbox-navigation-android/tree/publisher-staging/2.0.0-beta.4
        - staging docs https://docs.tilestream.net/android/navigation/api-reference/
        - staging docs v2.0.0-beta.4 https://docs.tilestream.net/android/navigation/api/2.0.0-beta.4/-modules.html
        <br/>**cc** @mapbox/navigation-android

### CODE REVIEW

**Review by colleenmcginnis — COMMENTED** [review]
Looks like you included `libnavigation-android`, which is empty. Was that intentional? 

image

**Comment by korshaknn** [comment]
@colleenmcginnis hm, I just run the script, as usual, don't know why `libnavigation-android` is here.

**Comment by RingerJK** [comment]
@korshaknn that's not expected, need to remove libnavigation-android from dokka and re-create docs

**Review by colleenmcginnis — APPROVED** [review]
Looks as I'd expect. 👍

**Pull request merged**
