### PR TITLE
Initialize metric session state in constructor

### LINKED ISSUE #717: Crash in completely unrelated activity.
In my app the flow is: `StartupActivity` -> `LoginActivity` -> `ShuttleListActivity` -> `RidesActivity` -> `NavigationActivity`.  The user bounces between the `RidesActivity` and `NavigationActivity` most of the time.  There is 0 usage of any mapbox code until the `NavigationActivity` - nowhere else does the code use mapbox (well, except to initialize it with the access token / keys / etc. in the Application context).

Here's the log that i captured:
```
1	|	20:20:54:586 (UTC)	|	D/QR/Application onCreate(388194908)
2	|	20:20:54:838 (UTC)	|	D/QR/Application onTrimMemory(388194908,15)
3	|	20:20:54:864 (UTC)	|	D/QR/Analytics logEvent(HttpRequest, method,PUT,encodedPath,/api/v1/device/driver,encodedQuery,,host,api.goquickride.com,isHttps,true)
4	|	20:20:54:892 (UTC)	|	D/QR/RidesActivity onCreate(285281509,null)
5	|	20:20:55:017 (UTC)	|	
6	|	20:20:55:114 (UTC)	|	D/QR/RidesActivity onStart(285281509)
7	|	20:20:55:115 (UTC)	|	D/QR/RidesActivity onResume(285281509)
8	|	20:20:55:202 (UTC)	|	W/QR/DriverUpdatesWS Socket already open
9	|	20:20:55:202 (UTC)	|	D/QR/DriverUpdatesWS Opening WebSocket
10	|	20:20:55:225 (UTC)	|	D/QR/Analytics logEvent(HttpRequest, method,GET,encodedPath,/socket/driver-updates,encodedQuery,,host,api.goquickride.com,isHttps,true)
11	|	20:20:55:242 (UTC)	|	
12	|	20:20:55:302 (UTC)	|	D/QR/Analytics logEvent(HttpRequest, method,GET,encodedPath,/api/v1/params,encodedQuery,,host,api.goquickride.com,isHttps,true)
13	|	20:20:55:371 (UTC)	|	
14	|	20:20:55:592 (UTC)	|	D/QR/Analytics logEvent(HttpRequest, method,PUT,encodedPath,/api/v1/device/push_token,encodedQuery,,host,api.goquickride.com,isHttps,true)
15	|	20:20:55:595 (UTC)	|	
16	|	20:20:55:600 (UTC)	|	D/QR/Analytics logEvent(HttpRequest, method,GET,encodedPath,/api/v1/station/1079/shuttle/3/ride,encodedQuery,states=WAITING_FOR_PICKUP&states=EN_ROUTE&offset=0&limit=9999,host,api.goquickride.com,isHttps,true)
17	|	20:20:55:707 (UTC)	|	
18	|	20:20:55:780 (UTC)	|	D/QR/App   Device token: 01b827ae-a5cb-4407-af20-7b7f3514856c
19	|	20:20:55:780 (UTC)	|	D/QR/App     Push token: cyeyiTnTzco:APA91bEezxQ4KO9iCY6NmCUV6gfIlAwv1ZUl20VTy1jocl429UgQo_zFq6gmXpLlaQflsI1nqigDgAsAxXUyknQrvU404Gh0KHDwZ9RPHYz34zI2MEVZZNARF0lm94qx7EAd1mq4FQN3
20	|	20:20:55:781 (UTC)	|	D/QR/App   Access token: 1426e3726a014d30c3de40e71c8ffe5a0e602532594d2f57e32b822b65b25a3b61ec2c554a181e5eae546f9f3db41d128ade524835bd64d56aee29067f4498cc76b9fc671b5fbd8f37311d1d6c133ee3c6880972949ba395798b4ccb7d16065b
21	|	20:20:55:846 (UTC)	|	D/QR/App     Station id: 1079
22	|	20:20:55:846 (UTC)	|	D/QR/App     Shuttle id: 3
23	|	20:20:55:846 (UTC)	|	
24	|	20:20:55:870 (UTC)	|	D/QR/Dialogs v: 2.0.58, currentAndroidVersion: 2.0.40
25	|	20:20:56:037 (UTC)	|	D/QR/Analytics logEvent(RidesLoaded, )
26	|	20:20:56:156 (UTC)	|	
27	|	20:20:56:191 (UTC)	|	
28	|	20:20:56:262 (UTC)	|	
29	|	20:20:56:297 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176662,"lon":-122.3521649,"speed":0.0,"direction":0.0})
30	|	20:20:56:345 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176664,"lon":-122.3521632,"speed":0.0,"direction":0.0})
31	|	20:20:56:393 (UTC)	|	
32	|	20:20:56:455 (UTC)	|	
33	|	20:20:57:715 (UTC)	|	
34	|	20:20:57:761 (UTC)	|	
35	|	20:20:57:791 (UTC)	|	
36	|	20:20:57:817 (UTC)	|	
37	|	20:20:58:120 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176675,"lon":-122.3521577,"speed":0.0,"direction":0.0})
38	|	20:20:59:122 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176675,"lon":-122.3521577,"speed":0.0,"direction":0.0})
39	|	20:21:00:123 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176675,"lon":-122.3521576,"speed":0.0,"direction":0.0})
40	|	20:21:02:134 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176675,"lon":-122.3521575,"speed":0.0,"direction":0.0})
41	|	20:21:03:147 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176677,"lon":-122.3521574,"speed":0.0,"direction":0.0})
42	|	20:21:05:126 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176682,"lon":-122.3521572,"speed":0.0,"direction":0.0})
43	|	20:21:06:133 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176691,"lon":-122.3521566,"speed":0.0,"direction":0.0})
44	|	20:21:08:133 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176695,"lon":-122.3521565,"speed":0.0,"direction":0.0})
45	|	20:21:09:131 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176698,"lon":-122.3521564,"speed":0.0,"direction":0.0})
46	|	20:21:11:128 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176703,"lon":-122.3521562,"speed":0.0,"direction":0.0})
47	|	20:21:12:129 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176705,"lon":-122.3521561,"speed":0.0,"direction":0.0})
48	|	20:21:14:127 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176712,"lon":-122.3521559,"speed":0.0,"direction":0.0})
49	|	20:21:15:136 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176715,"lon":-122.3521558,"speed":0.0,"direction":0.0})
50	|	20:21:16:125 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176716,"lon":-122.3521559,"speed":0.0,"direction":0.0})
51	|	20:21:17:129 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176718,"lon":-122.3521559,"speed":0.0,"direction":0.0})
52	|	20:21:18:135 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176719,"lon":-122.352156,"speed":0.0,"direction":0.0})
53	|	20:21:19:128 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.617672,"lon":-122.352156,"speed":0.0,"direction":0.0})
54	|	20:21:20:142 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.617672,"lon":-122.352156,"speed":0.0,"direction":0.0})
55	|	20:21:22:122 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176721,"lon":-122.3521561,"speed":0.0,"direction":0.0})
56	|	20:21:23:126 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176721,"lon":-122.3521561,"speed":0.0,"direction":0.0})
57	|	20:21:25:132 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176722,"lon":-122.3521562,"speed":0.0,"direction":0.0})
58	|	20:21:27:126 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176722,"lon":-122.3521562,"speed":0.0,"direction":0.0})
59	|	20:21:28:126 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176723,"lon":-122.3521562,"speed":0.0,"direction":0.0})
60	|	20:21:30:123 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176725,"lon":-122.3521561,"speed":0.0,"direction":0.0})
61	|	20:21:31:124 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176727,"lon":-122.352156,"speed":0.0,"direction":0.0})
62	|	20:21:32:135 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176729,"lon":-122.3521559,"speed":0.0,"direction":0.0})
63	|	20:21:33:134 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176731,"lon":-122.3521558,"speed":0.0,"direction":0.0})
64	|	20:21:35:135 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176736,"lon":-122.3521555,"speed":0.0,"direction":0.0})
65	|	20:21:36:134 (UTC)	|	D/QR/DriverUpdatesWS sendMessage(1062762466,{"lat":47.6176738,"lon":-122.3521554,"speed":0.0,"direction":0.0})
66	|	20:21:36:788 (UTC)	|	D/QR/RidesActivity onPause(285281509)
67	|	20:21:37:296 (UTC)	|	D/QR/RidesActivity onStop(285281509)
68	|	20:21:37:297 (UTC)	|	D/QR/Application onTrimMemory(388194908,20)
69	|	20:21:45:207 (UTC)	|	D/QR/StartupActivity onCreate(230282914,null)
70	|	20:21:45:275 (UTC)	|	D/QR/StartupActivity onStart(230282914)
71	|	20:21:45:276 (UTC)	|	D/QR/StartupActivity onResume(230282914)
72	|	20:21:45:381 (UTC)	|	
73	|	20:21:45:429 (UTC)	|	
74	|	20:21:45:785 (UTC)	|	
75	|	20:21:46:391 (UTC)	|	D/QR/Application onTrimMemory(388194908,15)
76	|	20:21:47:531 (UTC)	|	D/QR/StartupActivity onPause(230282914)
```

And here's the stack trace of the crash:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Date com.mapbox.services.android.navigation.v5.navigation.metrics.SessionState.startTimestamp()' on a null object reference
       at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.endSession(NavigationTelemetry.java:213)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationLifecycleMonitor.onActivityDestroyed(NavigationLifecycleMonitor.java:57)
       at android.app.Application.dispatchActivityDestroyed(Application.java:248)
       at android.app.Activity.onDestroy(Activity.java:1670)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:358)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
       at com.trello.rxlifecycle2.components.support.RxAppCompatActivity.onDestroy(RxAppCompatActivity.java:95)
       at com.gosuna.quickride.DriverApp.activities.BaseActivity.onDestroy(BaseActivity.java:88)
       at com.gosuna.quickride.DriverApp.activities.ride.RidesActivity.onDestroy(RidesActivity.java:204)
       at android.app.Activity.performDestroy(Activity.java:6235)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3808)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3839)
       at android.app.ActivityThread.access$1400(ActivityThread.java:162)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5431)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #717

### CODE REVIEW

**Comment by briandilley** [comment]
When will this be included in a release version?

**Comment by danesfeder** [comment]
@briandilley today, currently working on getting this merged and then releasing `0.10.0`

**Comment by briandilley** [comment]
sweet!

**Comment by briandilley** [comment]
I'm happy to invite a few mapbox developers to our github repo so that they can see how we're using it - perhaps it will help?

**Comment by danesfeder** [comment]
@briandilley Yeah, thank you, that would be great - you can invite me.  

As @Guardiola31337 explained, there's a bigger race issue causing this crash that we are trying to figure out that and we haven't produced in our own codebase.  This PR is more of a band-aid to prevent the crash.

**Comment by briandilley** [comment]
@danesfeder Can you share your email with me?  I'd like to potentially get you on slack too incase you have questions about the code.  I'll send an invite to the codebase now.

**Comment by danesfeder** [comment]
@briandilley Sure thing - `dan.nesfeder@mapbox.com`

**Comment by briandilley** [comment]
Cool, I sent you an invitation to our Slack :)

**Pull request merged**
