### PR TITLE
Bump NN 54.0.0

### PR DESCRIPTION
**Pull request by korshaknn**
### Description

Bump NN 54.0.0

### Changelog

```
<changelog>`RoadObjectMatcher` API changed. Added `cancelAll()` func, added `onMatchingCancelled(id: String)` callback to a `RoadObjectMatcherListener`, `cancel(roadObjectIds: List<String>)` handles a list of ids, not a single one.</changelog>
```

### CODE REVIEW

**Review by Guardiola31337 — APPROVED** [review]

**Comment by RingerJK** [comment]
I think we don't need a changelog for the PR 🤔 
```
<changelog>Bump NN 54.0.0</changelog>
```

**Comment by Guardiola31337** [comment]
> I think we don't need a changelog for the PR 🤔 
>```
><changelog>Bump NN 54.0.0</changelog>
>```

Could we include something around the breaking changes instead?

**Comment by korshaknn** [comment]
@RingerJK @Guardiola31337 changelog fixed

**Comment by Guardiola31337** [comment]
Going ahead and merging here 🚀

**Pull request merged**
