### PR TITLE
Move gradle_opts changes to circle yml

### PR DESCRIPTION
**Pull request by kmadsen**
This reverts commit d371e2bcad992696f5c4303ea7d42f3e73bc8efd.

## Description

Reverting https://github.com/mapbox/mapbox-navigation-android/pull/2968 because we're still seeing the issue

- [ ] I have added any issue links
- [ ] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

## Testing

Please describe the manual tests that you ran to verify your changes

- [ ] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR

### CODE REVIEW

**Comment by kmadsen** [comment]
Screen Shot 2020-05-13 at 12 07 06 PM

moving to cirlce yml works for build. now going to try adding to ui-tests-1_0

**Comment by Guardiola31337** [comment]
> Screen Shot 2020-05-13 at 12 07 06 PM
>
> moving to circle yml works for build. now going to try adding to ui-tests-1_0

Why isn't a problem for `build-1_0`? https://github.com/mapbox/mapbox-navigation-android/blob/a21086fcc39e284747d7376176851b4e3ba9f168/circle.yml#L445 We don't have any options there 🤔

**Comment by kmadsen** [comment]
yeah maybe we don't need any of the environment options? 

this passes ui-tests-1_0 now

**Comment by Guardiola31337** [comment]
> yeah maybe we don't need any of the environment options? 
>
> this passes ui-tests-1_0 now

If that works, let's add it to the rest of the builds for consistency similar to what we tried in https://github.com/mapbox/mapbox-navigation-android/pull/2967

**Comment by kmadsen** [comment]
> > yeah maybe we don't need any of the environment options?
> > this passes ui-tests-1_0 now
> 
> If that works, let's add it to the rest of the builds for consistency similar to what we tried in #2967

honestly don't like adding things that aren't needed. is it consistent, duplicated, or null operations?

**Comment by kmadsen** [comment]
I've submitted a request to CircleCI to see if they have other ways to diagnose memory issues. Only increasing memory, doesn't tell us what our issues are. They must get these questions frequently because here was the response. Sharing the links for reference and if anyone is interested.


[Exit code 137 - Out of memory](https://support.circleci.com/hc/en-us/articles/115014359648-Exit-code-137-Out-of-memory?auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo4MjgyMDksInVzZXJfaWQiOm51bGwsInRpY2tldF9pZCI6NzIzMzYsImRlZmxlY3Rpb25faWQiOjM2MDQyODgzNTA3NCwiYXJ0aWNsZXMiOlsxMTUwMTQzNTk2NDgsMTE1MDE1NzU0MjI4LDM2MDAyMTgxMjQ1M10sInRva2VuIjpudWxsLCJleHAiOjE1OTE5OTAxODF9.tdikV0VZvNdmJSsN2agBYnNtGpMBDywcS0T1fmQzNjY)
[Java memory issues (Gradle, Maven, Kotlin, Lein, Elasticsearch)](https://support.circleci.com/hc/en-us/articles/115015754228-Java-memory-issues-Gradle-Maven-Kotlin-Lein-Elasticsearch-?auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo4MjgyMDksInVzZXJfaWQiOm51bGwsInRpY2tldF9pZCI6NzIzMzYsImRlZmxlY3Rpb25faWQiOjM2MDQyODgzNTA3NCwiYXJ0aWNsZXMiOlsxMTUwMTQzNTk2NDgsMTE1MDE1NzU0MjI4LDM2MDAyMTgxMjQ1M10sInRva2VuIjpudWxsLCJleHAiOjE1OTE5OTAxODF9.tdikV0VZvNdmJSsN2agBYnNtGpMBDywcS0T1fmQzNjY)
[Common Android memory issues](https://support.circleci.com/hc/en-us/articles/360021812453-Common-Android-memory-issues?auth_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo4MjgyMDksInVzZXJfaWQiOm51bGwsInRpY2tldF9pZCI6NzIzMzYsImRlZmxlY3Rpb25faWQiOjM2MDQyODgzNTA3NCwiYXJ0aWNsZXMiOlsxMTUwMTQzNTk2NDgsMTE1MDE1NzU0MjI4LDM2MDAyMTgxMjQ1M10sInRva2VuIjpudWxsLCJleHAiOjE1OTE5OTAxODF9.tdikV0VZvNdmJSsN2agBYnNtGpMBDywcS0T1fmQzNjY)


Screen Shot 2020-05-13 at 12 48 37 PM

**Pull request merged**
