### PR TITLE
Fix recenter show logic by adding MoveListener again in lifecycle

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #1253 

@siavashabdoli thanks for all the time debugging this and writing this solution.  I pulled in your commit here so CI runs and we will get final 👀 from the rest of the team.

### CODE REVIEW

**Comment by Guardiola31337** [comment]
Have we considered calling `navigationMap.removeOnMoveListener(onMoveListener);` when in `onDestroy` instead of in `onStop`? Wouldn't that solve the "backgrounding" issue?

**Comment by Guardiola31337** [comment]
Pulled in the latest changes from https://github.com/mapbox/mapbox-navigation-android/pull/1253

This is ready for a final round of 👀 @danesfeder 

Thanks @siavashabdoli for the contribution and for addressing the comments 🙏

**Comment by danesfeder** [comment]
@Guardiola31337 looks good to me - feel free to give the final ✅

**Comment by danesfeder** [comment]
Thanks again @siavashabdoli 👍

**Comment by siavashabdoli** [comment]
You're welcome

**Pull request merged**
