### PR TITLE
Drop-in UI Theme Switching 

### PR DESCRIPTION
**Pull request by danesfeder**
Note: currently branched from rotation PR

Remaining Todo: 
- [x] Dark theme colors 
- [x] Extract constants
- [x] Text colors
- [x] < API 19 set colors without `?attr`
- [x] javadoc

### CODE REVIEW

**Comment by danesfeder** [comment]
Found that the crash was related to using custom attributes when setting the `Drawable` colors.  Created `v21` versions of the drawables with the attributes included then added version checks to set the drawable colors based on the given style.  

Still TODO:  setting the color of the recenter btn / progress bar

**Comment by danesfeder** [comment]
ezgif com-video-to-gif

**Comment by cammace** [comment]
Is it possible to keep the navigation puck facing the correct orientation? Can we open a ticket in the plugins repo if this is something that should be fixed inside that library?

**Comment by danesfeder** [comment]
@cammace I'm pretty this is only because of the `MockLocationEngine` restarting and shouldn't be an issue with actual engines

**Comment by Danny-James** [comment]
@danesfeder quick question, when these fixes are made, how do i know what i need to compile to get them/where do i find the latest version?

**Pull request merged**
