### PR TITLE
[WIP] Fix TransactionTooLargeException from MapboxNavigationNotification

### LINKED ISSUE #1188: MapboxNavigationNotification#updateNotificationViews TransactionTooLargeException
Run into the following 💥 while testing

```
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 524216 bytes
  at android.app.NotificationManager.notifyAsUser(NotificationManager.java:408)
  at android.app.NotificationManager.notify(NotificationManager.java:370)
  at android.app.NotificationManager.notify(NotificationManager.java:346)
  at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.updateNotificationViews(MapboxNavigationNotification.java:150)
  at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.updateNotification(MapboxNavigationNotification.java:72)
  at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.updateNavigationNotification(NavigationNotificationProvider.java:23)
  at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:33)
  at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:97)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6669)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: android.os.TransactionTooLargeException: data parcel size 524216 bytes
  at android.os.BinderProxy.transactNative(Native Method)
  at android.os.BinderProxy.transact(Binder.java:1127)
  at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:1558)
  at android.app.NotificationManager.notifyAsUser(NotificationManager.java:405)
  at android.app.NotificationManager.notify(NotificationManager.java:370) 
  at android.app.NotificationManager.notify(NotificationManager.java:346) 
  at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.updateNotificationViews(MapboxNavigationNotification.java:150) 
  at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.updateNotification(MapboxNavigationNotification.java:72) 
  at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.updateNavigationNotification(NavigationNotificationProvider.java:23) 
  at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:33) 
  at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:97) 
  at android.os.Handler.handleCallback(Handler.java:873) 
  at android.os.Handler.dispatchMessage(Handler.java:99) 
  at android.os.Looper.loop(Looper.java:193) 
  at android.app.ActivityThread.main(ActivityThread.java:6669) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

### PR DESCRIPTION
**Pull request by danesfeder**
Another attempt to fix #1188 

The goal here is to again remove the expanded `RemoteView`, hoping that updating both results in less `Parcel` data accumulating.  

I also thought that we could try to "catch and restart" the notification? 🤔 

```
   try {
      notificationManager.notify(NAVIGATION_NOTIFICATION_ID, notification);
    } catch (Exception exception) {
      notificationManager.cancel(NAVIGATION_NOTIFICATION_ID);
    }
```  

Another thought here would be to only update given a certain amount of updates.  So now we update every second + the data is different.  Maybe we should create a threshold (5, 10, 15 updates) before we update the UI?  Just another thought. 

I'm running a route from DC to SF right now so will keep an eye on this as the day progresses.

### CODE REVIEW

**Comment by danesfeder** [comment]
This seems to have help - the route I was running yesterday DC > SF did not crash after running for ~5 hours.

**Comment by Guardiola31337** [comment]
@danesfeder 
> I know you have an overnight testing method that I'd like to try as well 😆 

Got the chance to run this during last night 😄

Although the test run didn't reproduce the `TransactionTooLargeException` (yaay! 🎉) it got an ANR eventually 😥

These are the logs that were printed out:

```
01-31 12:10:28.923 775-789/? W/BroadcastQueue: Timeout of broadcast BroadcastRecord{df2002f u0 com.mapbox.scheduler_flusher} - receiver=android.os.BinderProxy@ad3665a, started 60010ms ago
01-31 12:10:28.923 775-789/? W/BroadcastQueue: Receiver during timeout: BroadcastFilter{9173568 u0 ReceiverList{8ce308b 7051 com.mapbox.services.android.navigation.app/10133/u0 remote:ad3665a}}
01-31 12:10:28.943 775-789/? I/ActivityManager: Skipping duplicate ANR: ProcessRecord{7979d81 7051:com.mapbox.services.android.navigation.app/u0a133} Broadcast of Intent { act=com.mapbox.scheduler_flusher flg=0x14 (has extras) }
```

After getting a bunch of ☝️ the trace for the ANR was logged out:

```
01-31 13:41:24.211 775-789/? E/ActivityManager: ANR in com.mapbox.services.android.navigation.app
    PID: 7051
    Reason: Broadcast of Intent { act=com.mapbox.scheduler_flusher flg=0x14 (has extras) }
    Load: 9.03 / 9.31 / 9.38
    CPU usage from 136745ms to 0ms ago:
      107% 7051/com.mapbox.services.android.navigation.app: 102% user + 5.3% kernel / faults: 1305591 minor
      1.6% 775/system_server: 1% user + 0.6% kernel / faults: 2022 minor 17 major
      0.7% 2329/mpdecision: 0% user + 0.7% kernel / faults: 2 minor
      0.7% 189/surfaceflinger: 0.2% user + 0.4% kernel / faults: 8 minor
      0.5% 929/com.android.systemui: 0.4% user + 0.1% kernel / faults: 677 minor 29 major
      0.4% 25938/com.google.android.gms.persistent: 0.4% user + 0% kernel / faults: 792 minor
      0.3% 206/sensors.qcom: 0% user + 0.2% kernel / faults: 70 minor
      0.3% 6903/ru.gavrikov.mocklocations: 0.1% user + 0.1% kernel / faults: 210 minor
      0.3% 131/ueventd: 0% user + 0.2% kernel
      0.1% 3/ksoftirqd/0: 0% user + 0.1% kernel
      0.1% 4397/kworker/u:1: 0% user + 0.1% kernel
      0.1% 13985/kworker/u:3: 0% user + 0.1% kernel
      0.1% 1038/wpa_supplicant: 0% user + 0% kernel
      0% 4798/com.google.android.apps.messaging: 0% user + 0% kernel / faults: 155 minor
      0% 9899/kworker/u:2: 0% user + 0% kernel
      0% 124/dhd_dpc: 0% user + 0% kernel
      0% 6628/kworker/0:2: 0% user + 0% kernel
      0% 7/kworker/u:0H: 0% user + 0% kernel
      0% 23974/kworker/0:2H: 0% user + 0% kernel
      0% 120/mmcqd/1: 0% user + 0% kernel
      0% 197/mediaserver: 0% user + 0% kernel / faults: 170 minor 1 major
      0% 430/mdss_fb0: 0% user + 0% kernel
      0% 4173/ksoftirqd/1: 0% user + 0% kernel
      0% 8/migration/0: 0% user + 0% kernel
      0% 187/lmkd: 0% user + 0% kernel
      0% 216/adbd: 0% user + 0% kernel / faults: 140 minor
      0% 96/irq/362-s3350: 0% user + 0% kernel
      0% 147/logd: 0% user + 0% kernel
      0% 4170/migration/1: 0% user + 0% kernel
      0% 11943/kworker/0:0H: 0% user + 0% kernel
      0% 12448/kworker/1:1H: 0% user + 0% kernel
      0% 17057/com.google.android.gm: 0% user + 0% kernel / faults: 2124 minor
      0% 2/kthreadd: 0% user + 0% kernel
      0% 123/dhd_watchdog_th: 0% user + 0% kernel
      0% 1727/com.google.android.gms: 0% user + 0% kernel / faults: 593 minor
      0% 2298/com.android.bluetooth: 0% user + 0% kernel / faults: 3050 minor
      0% 5876/logcat: 0% user + 0% kernel
      0% 15003/kworker/1:0H: 0% user + 0% kernel
      0% 16208/kworker/u:0: 0% user + 0% kernel
      0% 22472/com.android.vending: 0% user + 0% kernel / faults: 81 minor
      0% 122/wl_event_handle: 0% user + 0% kernel
      0% 136/flush-179:0: 0% user + 0% kernel
      0% 188/servicemanager: 0% user + 0% kernel
      0% 193/netd: 0% user + 0% kernel / faults: 4 minor
      0% 195/rild: 0% user + 0% kernel
      0% 203/bridgemgrd: 0% user + 0% kernel / faults: 135 minor
      0% 211/thermal-engine-hh: 0% user + 0% kernel
      0% 1480/com.android.phone: 0% user + 0% kernel / faults: 18 minor 2 major
      0% 1669/com.estrongs.android.pop: 0% user + 0% kernel / faults: 265 minor
     +0% 16907/kworker/0:1H: 0% user + 0% kernel
    54% TOTAL: 50% user + 3.7% kernel + 0% iowait + 0% softirq
    CPU usage from 1638ms to 2166ms later:
      105% 775/system_server: 45% user + 60% kernel / faults: 918 minor
        96% 780/Signal Catcher: 39% user + 56% kernel
        5.6% 789/ActivityManager: 3.7% user + 1.8% kernel
      9.3% 7051/com.mapbox.services.android.navigation.app: 5.6% user + 3.7% kernel / faults: 785 minor
        9.3% 7051/.navigation.app: 9.3% user + 0% kernel
        1.8% 7734/GLThread 14321: 1.8% user + 0% kernel
        1.8% 7777/mapbox_navigati: 1.8% user + 0% kernel
      1.5% 2329/mpdecision: 0% user + 1.5% kernel
        1.5% 2345/mpdecision: 0% user + 1.5% kernel
    47% TOTAL: 22% user + 25% kernel
```

And after some time, there was a binder transaction failure:

```
01-31 16:16:03.806 7051-7051/com.mapbox.services.android.navigation.app E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 2254684)
```

**Comment by Guardiola31337** [comment]
As suggested by @danesfeder I'll be running the same test with `master` code just in case https://github.com/mapbox/mapbox-navigation-android/pull/1691#issuecomment-459392147 is unrelated to #1188 - a different issue.

**Comment by Guardiola31337** [comment]
> I'll be running the same test with `master` code just in case https://github.com/mapbox/mapbox-navigation-android/pull/1691#issuecomment-459392147 is unrelated to #1188 - a different issue.

I run the same test pulling the code from `master` and I wasn't able to reproduce neither `TransactionTooLargeException` nor the ANR 🤔

Unfortunately, I re-tested this again and I was able to reproduce the ANR 😞
I got same exact behavior / logs as described above, so it's definitely something going on here.

cc @danesfeder

**Comment by danesfeder** [comment]
Going to close this for now as it doesn't seem to address the issue at hand, causing ANRs instead 😬 Let's keep the branch alive for now in case we decide to revisit.

**Pull request closed without merging**
