### PR TITLE
Bump NN dependency version to `119.0.4`

### PR DESCRIPTION
**Pull request by Guardiola31337**
### Description

- Bumps NN dependency version to `119.0.4`

cc @linexpe

### CODE REVIEW

**Comment by Guardiola31337** [comment]
Noting that `additional_alternative_is_not_force_to_invoke_alternatives_observer` `intstrumentation-test` https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/8480806035653990709/executions/bs.89ea469bdd045b8f/testcases/19 failed 👀 

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [RouteAlternativesIdlingResource] to become idle timed out
at androidx.test.espresso.Espresso.onIdle(Espresso.java:15)
at androidx.test.espresso.Espresso.onIdle(Espresso.java:1)
at com.mapbox.navigation.instrumentation_tests.core.RouteAlternativesTest$additional_alternative_is_not_force_to_invoke_alternatives_observer$5.invoke(RouteAlternativesTest.kt:274)
at com.mapbox.navigation.instrumentation_tests.core.RouteAlternativesTest$additional_alternative_is_not_force_to_invoke_alternatives_observer$5.invoke(RouteAlternativesTest.kt:273)
at com.mapbox.navigation.instrumentation_tests.utils.history.MapboxHistoryTestRule.stopRecordingOnCrash(MapboxHistoryTestRule.kt:71)
at com.mapbox.navigation.instrumentation_tests.core.RouteAlternativesTest.additional_alternative_is_not_force_to_invoke_alternatives_observer(RouteAlternativesTest.kt:273)
... 42 trimmed
Caused by: java.util.concurrent.ExecutionException: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [RouteAlternativesIdlingResource] to become idle timed out
at java.util.concurrent.FutureTask.report(FutureTask.java:123)
at java.util.concurrent.FutureTask.get(FutureTask.java:193)
at androidx.test.espresso.Espresso.onIdle(Espresso.java:10)
... 48 more
Caused by: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [RouteAlternativesIdlingResource] to become idle timed out
at androidx.test.espresso.IdlingPolicy.handleTimeout(IdlingPolicy.java:4)
at androidx.test.espresso.base.UiControllerImpl$5.resourcesHaveTimedOut(UiControllerImpl.java:1)
at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleTimeout(IdlingResourceRegistry.java:4)
at androidx.test.espresso.base.IdlingResourceRegistry$Dispatcher.handleMessage(IdlingResourceRegistry.java:6)
at android.os.Handler.dispatchMessage(Handler.java:102)
at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
at androidx.test.espresso.Espresso$1.run(Espresso.java:1)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

cc @dzinad @VysotskiVadim @RingerJK

**Comment by Guardiola31337** [comment]
It seems that `119.0.4` reintroduced https://github.com/mapbox/mapbox-navigation-android/blob/4b430898a1cc1d3f356a0a50fde93567706ff890/instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt#L194-L200 as https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6051051744197061301/executions/bs.7ffe6ca8c4b7991b/testcases/19 is failing consistently.

cc @RingerJK @mskurydin @dkositsyn

**Comment by dkositsyn** [comment]
> It seems that NN `v119.0.4` reintroduced
> 
> https://github.com/mapbox/mapbox-navigation-android/blob/4b430898a1cc1d3f356a0a50fde93567706ff890/instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt#L194-L200
> 
> as https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6051051744197061301/executions/bs.7ffe6ca8c4b7991b/testcases/19 is failing consistently.
> cc @RingerJK @mskurydin @dkositsyn

I know we've updated expected behaviour. Let's ask @averkhaturau for more details.

/cc @linexpe

**Comment by RingerJK** [comment]
It seems that the test is flaky, it passes on my side

**Comment by Guardiola31337** [comment]
> looks like the same issue in https://github.com/mapbox/mapbox-navigation-android/pull/6659#discussion_r1036160069

Added same workaround from https://github.com/mapbox/mapbox-navigation-android/pull/6659 https://github.com/mapbox/mapbox-navigation-android/pull/6656/commits/aefb1931b10fbcc33167fd5833e512c7761ed604

cc @RingerJK @LukasPaczos

**Review by RingerJK — APPROVED** [review]

**Comment by Guardiola31337** [comment]
Now it failed `history_recording_observer_ensures_first_set_route_event` https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/7011804890728890554/executions/bs.728fdb8d4fdbf1a9/testcases/5 👀 

```
java.lang.NullPointerException
at com.mapbox.navigation.instrumentation_tests.core.HistoryRecordingStateChangeObserverTest$history_recording_observer_ensures_first_set_route_event$1.invokeSuspend(HistoryRecordingStateChangeObserverTest.kt:354)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
at com.mapbox.navigation.instrumentation_tests.core.HistoryRecordingStateChangeObserverTest$awaitStopActiveGuidanceRecording$2$observer$1$onShouldStopRecording$1.onSaved(HistoryRecordingStateChangeObserverTest.kt:462)
at com.mapbox.navigation.core.history.MapboxHistoryRecorder.stopRecording$lambda-2$lambda-1(MapboxHistoryRecorder.kt:63)
at com.mapbox.navigation.core.history.MapboxHistoryRecorder.$r8$lambda$YnMgKxAxhgNPiSCf6sQIkMwHe9U(Unknown Source:0)
at com.mapbox.navigation.core.history.MapboxHistoryRecorder$$ExternalSyntheticLambda0.run(Unknown Source:2)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:335)
at android.os.Looper.loopOnce(Looper.java:186)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

cc @dzinad @RingerJK @VysotskiVadim

**Comment by dzinad** [comment]
> Now it failed history_recording_observer_ensures_first_set_route_event https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/7011804890728890554/executions/bs.728fdb8d4fdbf1a9/testcases/5 👀

I think it should be fixed via https://github.com/mapbox/mapbox-navigation-android/pull/6525.

**Pull request merged**
