### PR TITLE
Directions List Dropdown

### PR DESCRIPTION
**Pull request by danesfeder**
- Clicking the top banner will reveal the list of directions rather than an option from the bottomsheet

TODO:
- [x] Mirror banner view for each ViewHolder
- [x] Handle landscape
- [x] Handle back press
- [x] Clean up / docs

### CODE REVIEW

**Comment by danesfeder** [comment]
@ericrwolfe w/o updated banner views 

ezgif com-video-to-gif

**Comment by cammace** [comment]
Love it, for the direction item line breaker next to the `0.2mi`, can/should we make this a lighter gray? Has a designer looked over this or is this entire directions sheet designed by you @danesfeder?

screen shot 2017-10-24 at 6 43 37 pm

**Comment by Danny-James** [comment]
@danesfeder will this also include my request? #403

**Comment by danesfeder** [comment]
@Danny-James yeah we will handle back press in this PR (see TODO)

**Pull request merged**
