### PR TITLE
move recenter and summaryBehavior logic to Navigation Presenter

### PR DESCRIPTION
**Pull request by siavashabdoli**
Some logic related things was handled in view and cause I face some problem there I refactored there presenter. I don't know exactly why the presenter was initialized in onMapReady so I create some method for that as well.
Also I wrote automatic recenter for this part I will send merge request for that feature as well

### CODE REVIEW

**Comment by siavashabdoli** [comment]
@danesfeder can you review this one? I tested this already.

**Comment by siavashabdoli** [comment]
sorry I didn't push one of my commits. it's now completed also you can see the pr #748 for full feature. but if you don't want the recenter one consider merge this logic refactor to prevent UI from doing any logic and try to implement "passive view"

**Comment by danesfeder** [comment]
@siavashabdoli Thanks for this contribution!  Just wondering, is this logic included in #748?

**Comment by siavashabdoli** [comment]
@danesfeder yes it's already inculded in #748

**Comment by danesfeder** [comment]
@siavashabdoli cool, going to take a look at #748 - closing this as a duplicate (code included in #748)

**Pull request closed without merging**
