### PR TITLE
adjustments for the route line

### PR DESCRIPTION
**Pull request by cafesilencio**
## Description

Adjustments for the route line animation for long routes.

- [x] I have added any issue links
- [ ] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

### Goal

Make the line vanishing point stay more consistent with the puck location.

### Implementation

Adjustments to the animation delay and increased the decimal precision for percent distance traveled.

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make 1.0-core-update-api` (Core) / `$> make 1.0-ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs

### CODE REVIEW

**Comment by Guardiola31337** [comment]
@cafesilencio 
Took this for a spin and run into 👇 

examples_test_app_line_route_becomes_invisible

The route line becomes invisible somehow 🤔 I've tested the same scenario in `master` and couldn't reproduce.

BTW, shouldn't we address any PR against `master` and then cherry-pick into the release branch?

**Comment by cafesilencio** [comment]
@Guardiola31337 yes but I wanted a small adjustment for the route line. Most of what's in this PR is in the commit: https://github.com/mapbox/mapbox-navigation-android/commit/90dd906e70714c0403f7fc20ea4ef136a93a75e0.  There were other changes in the MapRouteLine that were made after the cutoff for this release that would get included if I created a PR against master.

**Comment by Guardiola31337** [comment]
The issue may be a performance / memory issue as I'm testing with a Nexus 5 that is running out of space and I can only reproduce when setting a really long route.

cc @cafesilencio

**Comment by Guardiola31337** [comment]
> yes but I wanted a small adjustment for the route line. Most of what's in this PR is in the commit: https://github.com/mapbox/mapbox-navigation-android/commit/90dd906e70714c0403f7fc20ea4ef136a93a75e0.  There were other changes in the MapRouteLine that were made after the cutoff for this release that would get included if I created a PR against master.

Does that mean that https://github.com/mapbox/mapbox-navigation-android/commit/90dd906e70714c0403f7fc20ea4ef136a93a75e0 includes all the changes from this PR or something else? If something else, do we want to cherry-pick them into the release branch? If so, feel free to cherry-pick it directly in here.

**Pull request closed without merging**
