### PR TITLE
delay first notification update

### PR DESCRIPTION
**Pull request by Zayankovsky**
### Description
Workaround for #2604. For some reason updating the notification right after starting foreground service does not work sometimes. The issue can be reproduced in a separate project without the SDK as well. 

### Changelog

```
<changelog>Fixed an issue where navigation notification could show partial data with a wrong icon</changelog>
```

### CODE REVIEW

**Review by Guardiola31337 — COMMENTED** [review]
Took this for a quick spin and it's promising so far. Haven't been able to reproduce. Will keep testing and report back here.

**Review by Guardiola31337 — APPROVED** [review]
Kept testing this downstream and couldn't reproduce the issue. Let's merge it as is for now and we can revisit the implementation later if we come up with a better approach.

Thanks for taking care of this @Zayankovsky

**Comment by kmadsen** [comment]
Is this being backported?

**Comment by Guardiola31337** [comment]
Nope, but we should.

**Pull request merged**
