### PR TITLE
bump NN to 123.3.3

### PR DESCRIPTION
**Pull request by dzinad**

### CODE REVIEW

**Comment by Guardiola31337** [comment]
`additional_alternative_is_not_force_to_invoke_alternatives_observer` and `updateLayerElevationTest` failed https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/5494623481020856955/executions/bs.d23d3650427c9b04/test-cases 🤔 

cc @dzinad

**Comment by Guardiola31337** [comment]
After re-running there's a new failure (different from the previous ones) `clearRoutesTest` ❌ https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/8890790151784003202/executions/bs.d4715891b229411/test-cases

cc @dzinad

**Comment by Guardiola31337** [comment]
Again, a different one 😞 `multipleSetRouteCall_longAndShortRouteSameConsumerTest` https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/7383456711390845004/executions/bs.83e55cafa9828a4c/test-cases

**Review by Guardiola31337 — APPROVED** [review]

**Comment by dzinad** [comment]
Looks like all the tests except for `additional_alternative_is_not_force_to_invoke_alternatives_observer ` failed because of some device issues (they failed without a stacktrace or error message (just "FAILED") and no crashes).
`additional_alternative_is_not_force_to_invoke_alternatives_observer` had been a bit flaky before. We need to investigate, but looks like nothing critical.

**Pull request merged**
