### PR TITLE
Add changelog for 1.3.0-alpha.2

### PR DESCRIPTION
**Pull request by kmadsen**
### Description

We're releasing 1.3.0-alpha.2 earlier than usual to dig into faster polling rates

### CODE REVIEW

**Comment by LukasPaczos** [comment]
Missing https://github.com/mapbox/mapbox-navigation-android/pull/3781 and https://github.com/mapbox/mapbox-navigation-android/pull/3791.

**Comment by Guardiola31337** [comment]
> https://github.com/mapbox/mapbox-navigation-android/pull/3791

I think that's not needed as was already cherry-picked into `1.2` https://github.com/mapbox/mapbox-navigation-android/pull/3796

**Comment by kmadsen** [comment]
> Missing #3781 and #3791.

🤔  hmm i went through the commit list. and #3781 was added before 1.3.0-alpha.1. 

Screen Shot 2020-11-19 at 12 37 52 PM

**Comment by Guardiola31337** [comment]
> I think that's not needed as was already cherry-picked into `1.2` https://github.com/mapbox/mapbox-navigation-android/pull/3796

To be technically correct, that was added in `1.3.0-alpha.2` and not available in `1.3.0-alpha.1` so yeah let's include both 👍

**Review by Guardiola31337 — APPROVED** [review]

**Comment by LukasPaczos** [comment]
>  #3781 was added before 1.3.0-alpha.1

The changelog commit was late IIRC.

**Pull request merged**
