### PR TITLE
Include 'exit roundabout' in Navigation Constants

### PR DESCRIPTION
**Pull request by brentnd**
Update maneuver types based on latest values and order documented.
* Adds `exit roundabout`
* Adds `STEP_MANEUVER_TYPE_EXIT_ROUNDABOUT` and `STEP_MANEUVER_TYPE_EXIT_ROTARY` to maneuver type string definition.
* Orders maneuver types to match documentation.

### CODE REVIEW

**Comment by Guardiola31337** [comment]
Hey @brentnd 👋 great catch here and thank you for this contribution!

Would you mind adding `STEP_MANEUVER_TYPE_EXIT_ROUNDABOUT and STEP_MANEUVER_TYPE_EXIT_ROTARY` to https://github.com/mapbox/mapbox-navigation-android/blob/a7b2da23b50614c172462f5bab9e8c751fce21a6/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverView.java#L57 `STEP_MANEUVER_TYPE_EXIT_ROUNDABOUT` to https://github.com/mapbox/mapbox-navigation-android/blob/a7b2da23b50614c172462f5bab9e8c751fce21a6/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverView.java#L64 and `STEP_MANEUVER_TYPE_EXIT_ROUNDABOUT` to https://github.com/mapbox/mapbox-navigation-android/blob/a7b2da23b50614c172462f5bab9e8c751fce21a6/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/instruction/maneuver/ManeuverViewMap.java#L28

Once addressed we can cherry-pick your commit to a new branch so our CI will kick off.  Thanks again, and let us know if you have any questions. 🚀

---

[Offtopic] Reviewing this contribution I realized that we're not mapping all maneuver types available in https://github.com/mapbox/mapbox-navigation-android/blob/a7b2da23b50614c172462f5bab9e8c751fce21a6/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/utils/ManeuverMap.java#L35 `ManeuverMap` maps the maneuver types with the icons shown in the foreground notification. I know that we've discussed StyleKit vs drawables vs vectors (SVG) before. For consistency, I think it'd be great to bring this conversation up again and try to agree on a solution that works across the whole codebase.  I'll cut a new ticket if you think we should address this. Opinions? Thoughts? @mapbox/navigation-android

**Comment by brentnd** [comment]
Good catch, I must not have looked very hard for other usages. I'll add your suggestions.

**Comment by Guardiola31337** [comment]
@brentnd 
> Pushed the requested changes

Awesome! Thanks for addressing the feedback 🙏 

> Let me know if you want me to squash those 2 commits.

Yeah! That'd be 💯

Thanks again!

**Comment by brentnd** [comment]
Done.

**Comment by Guardiola31337** [comment]
Following up on this PR in #1628

Again, thanks @brentnd for the contribution 🙇

Closing here.

**Pull request closed without merging**
