### PR TITLE
Docs v2.0.0-alpha.10

### PR DESCRIPTION
**Pull request by RingerJK**
**Docs v2.0.0-alpha.10**
        <br/>**Staging**:
        - github/publisher-staging https://github.com/mapbox/mapbox-navigation-android/tree/publisher-staging/2.0.0-alpha.10
        - staging docs https://docs.tilestream.net/android/navigation/api-reference/
        - staging docs v2.0.0-alpha.10 https://docs.mapbox.com/android/navigation/api/2.0.0-alpha.10/-modules.html
        <br/>**cc** @mapbox/navigation-android

### CODE REVIEW

**Review by colleenmcginnis — COMMENTED** [review]
@RingerJK I'm seeing two modules that might be missing the kind of label/name that other modules have: 

- "libnavui-resources" (this is also empty when clicked)
- "libnavui-util"

image

**Comment by RingerJK** [comment]
@colleenmcginnis thanks for addressed! Recreated docs 🚀

**Comment by colleenmcginnis** [comment]
It looks like you may be committing some extra files here:

```
examples/src/main/res/values/mapbox_access_token.xml
instrumentation-tests/src/main/res/values/mapbox_access_token.xml
libnavigation-core/src/main/assets/sdk_versions/com.mapbox.navigation.core
libnavigation-core/src/test/resources/mobile-event-schemas.jsonl.gz
libnavigation-ui/src/main/assets/sdk_versions/com.mapbox.navigation.ui
libnavui-base/src/main/assets/sdk_versions/com.mapbox.navigation.ui.base
libnavui-maneuver/src/main/assets/sdk_versions/com.mapbox.navigation.ui.maneuver
libnavui-maps/src/main/assets/sdk_versions/com.mapbox.navigation.ui.maps
libnavui-resources/src/main/assets/sdk_versions/com.mapbox.navigation.ui.resources
libnavui-tripprogress/src/main/assets/sdk_versions/com.mapbox.navigation.ui.tripprogress
libnavui-util/src/main/assets/sdk_versions/com.mapbox.navigation.ui.utils
libnavui-voice/src/main/assets/sdk_versions/com.mapbox.navigation.ui.voice
test-app/src/main/res/values/mapbox_access_token.xml
```

I'm not sure if there's harm in committing some of these other than them cluttering the repo, but you probably don't want to commit the three `mapbox_access_token.xml` files.

**Comment by RingerJK** [comment]
> I'm not sure if there's harm in committing some of these other than them cluttering the repo, but you probably don't want to commit the three `mapbox_access_token.xml` files.

my bad, fixed

**Review by colleenmcginnis — APPROVED** [review]
Looks good to me now. 👍

**Pull request merged**
