### PR TITLE
update camera paddings to account for speed info view and action buttons

### PR DESCRIPTION
**Pull request by Zayankovsky**
### Screenshots or Gifs
| Before | After |
| --- | --- |
| before | after |

### CODE REVIEW

**Comment by tomaszrybakiewicz** [comment]
I don't think we need to do that. I'll leave it up to you, @abhishek1508 to decide.

**Comment by abhishek1508** [comment]
Yeah I wouldn't do this change either. Ideally, when the user switches to `RouteOverview` state, that indicates that the user wants to see more of the route and less of other view overlays. I would ideally remove these overlays when in overview mode to let the user see more of the map and route. This would become more realistic when you start to think about search along route. In this case, we would need to show search results along the route. Hence definite need to remove these overlays. 

What do you think @stnikita1 ?

**Comment by Zayankovsky** [comment]
By the way, we encountered similar issues with the following camera as well:

**Comment by korshaknn** [comment]
AG paddings should be fixed I think

**Comment by stnikita1** [comment]
> Yeah I wouldn't do this change either. Ideally, when the user switches to `RouteOverview` state, that indicates that the user wants to see more of the route and less of other view overlays. I would ideally remove these overlays when in overview mode to let the user see more of the map and route. This would become more realistic when you start to think about search along route. In this case, we would need to show search results along the route. Hence definite need to remove these overlays.

The picture "after" looks great. In overview mode we don't need a street name because we don't actually see the route we are on. So there

**Comment by stnikita1** [comment]
> Yeah I wouldn't do this change either. Ideally, when the user switches to `RouteOverview` state, that indicates that the user wants to see more of the route and less of other view overlays. I would ideally remove these overlays when in overview mode to let the user see more of the map and route. This would become more realistic when you start to think about search along route. In this case, we would need to show search results along the route. Hence definite need to remove these overlays.
> 
> What do you think @stnikita1 ?
The picture "after" looks great! In overview mode, we don't need a street name because we don't actually see the route we are on. And so there will still be space for the route at the bottom.
@abhishek1508 What overlays are you talking about?

**Comment by Zayankovsky** [comment]
@abhishek1508 where are we here? I believe we can't hide the action buttons in Overview mode, because these buttons are used to control the camera and the issue with these buttons is also present in Following mode. Hiding the speed info view is an option, although this will make the camera frame non-symmetrical.

**Comment by abhishek1508** [comment]
> @abhishek1508 where are we here? I believe we can't hide the action buttons in Overview mode, because these buttons are used to control the camera and the issue with these buttons is also present in Following mode. Hiding the speed info view is an option, although this will make the camera frame non-symmetrical.

I would suggest to close this PR, because with the latest changes we will be doing in Drop-In UI action buttons should not be visible in route preview state. The camera paddings and behaviors will change slightly as well and we can revisit the issue.

**Pull request closed without merging**
