### PR TITLE
Update Nav Native to v87.0.1 and mapbox-java to 6.3.0-beta.1

### PR DESCRIPTION
**Pull request by LukasPaczos**

### CODE REVIEW

**Review by Zayankovsky — APPROVED** [review]

**Comment by LukasPaczos** [comment]
There's one Java Pending Exception caught by a robo test in the replay example. I'm unable to reproduce so far so I think we can merge and iterate from there.

**Comment by Guardiola31337** [comment]
I was able to reproduce locally.

The crash was:

```
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err: kotlin.UninitializedPropertyAccessException: lateinit property navigationCamera has not been initialized
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at com.mapbox.navigation.examples.core.ReplayHistoryActivity$locationObserver$1.onNewLocationMatcherResult(ReplayHistoryActivity.kt:219)
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateLocationMatcherResult(MapboxTripSession.kt:628)
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateLocationMatcherResult(MapboxTripSession.kt:59)
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at com.mapbox.navigation.core.trip.session.MapboxTripSession$navigatorObserver$1.onStatus(MapboxTripSession.kt:270)
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:335)
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at android.os.Looper.loopOnce(Looper.java:161)
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at android.os.Looper.loop(Looper.java:288)
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7842)
2022-01-28 14:42:34.104 13990-13990/com.mapbox.navigation.examples W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-01-28 14:42:34.105 13990-13990/com.mapbox.navigation.examples W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2022-01-28 14:42:34.105 13990-13990/com.mapbox.navigation.examples W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Making `navigationCamera` nullable fixes it. Apparently with the latest version of NN we're getting a new location matcher result earlier (before the style is loaded) causing the crash. In any case, it's a setup issue that we can fix later.

**Comment by LukasPaczos** [comment]
I see, that makes sense. Seeing a Java Pending Exception made me think it's an example problem and nothing serious, thanks for confirming :+1:

**Comment by Guardiola31337** [comment]
Cut a ticket https://github.com/mapbox/mapbox-navigation-android/issues/5424

**Pull request merged**
