### PR TITLE
replaced algorithm for the vanishing route line to previous iteration…

### PR DESCRIPTION
**Pull request by cafesilencio**
##Description

Reverting the algorithm for the vanishing route line to a version that was more tested and isn't dependent on the distance remaining from the progress updates.  There was a bug reported that is currently unreproducible and I think going to this more tested algorithm that doesn't depend on anything but the location from the maps animator may resolve the issue. Merging this PR will give us some time to test in 1Tap.

- [ ] I have added any issue links
- [ ] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [ ] I have added the appropriate milestone and project boards

## Testing

- [ ] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [ ] I have tested via a test drive, or a simulation/mock location app
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have updated the `CHANGELOG` including this PR
- [ ] We might need to update / push `api/current.txt` files after running `$> make core-update-api` (Core) / `$> make ui-update-api` (UI) if there are changes / errors we're 🆗 with (e.g. `AddedMethod` changes are marked as errors but don't break SemVer) 🚀 If there are SemVer breaking changes add the `SEMVER` label. See [Metalava](https://github.com/mapbox/mapbox-navigation-android/blob/master/docs/metalava.md) docs

### CODE REVIEW

**Comment by LukasPaczos** [comment]
Any thoughts on this behavior @cafesilencio? Traveling from left to right, and then making a u-turn in place. We kept moving the vanishing point, even though the car was traveling in the opposite direction until we got a reroute (reroute was in the wrong direction but that's a different story).
ezgif com-optimize (74)

**Comment by cafesilencio** [comment]
That's a difficult case because the vanishing point update can only work with the route it has. Until the progress update listener gets a new route, from the reroute,  i"m not sure what can be done.  There is a something in place already that checks the distance of the puck from the route line but in your example that doesn't help because the puck is close enough to the route line. Pablo put in a fix that should have taken care of the reroute going in the correct direction. This is the first time I've seen that fix not being successful.

@Guardiola31337

**Comment by LukasPaczos** [comment]
@cafesilencio why is the value of the portion traveled increasing, if we're going backwards on the route? I would expect the vanishing point to still be stickied to the puck, not go in the opposing direction.

**Comment by cafesilencio** [comment]
I"m going to close this in favor of some tweaks on a different branch.

**Pull request closed without merging**
