### PR TITLE
Update Transifex translations

### LINKED ISSUE #1077: Update description_navigation_view_ui key in Transifex
In https://github.com/mapbox/mapbox-navigation-android/pull/1076 we've changed one of the keys of an already translated string. In order to avoid the community to translate the "new" string again we should update it in Transifex somehow.

Old key 👉 `description_navigation_view_ui`
New key 👉 `description_navigation_launcher`

I know that it's possible to sync up Transifex uploading the different `strings.xml` but I also guess that should be an easier way for this kind of situations (like updating the key through the Transifex UI so it gets populated through the already translations). Do you know @1ec5? Could you help here?

cc'ing @danesfeder and @langsmith that have also worked with Transifex

### PR DESCRIPTION
**Pull request by danesfeder**
Closes #1077 

Pulled down new translations and pushed updated variable naming from #1076

### CODE REVIEW

**Comment by Guardiola31337** [comment]
At this point this PR doesn't close #1077 

Don’t want the community to translate the "new" string again. As explained it'd be great to

- Update the key in Transifex

or

- Force push the already translated `strings.xml` files (with the new key)

**Comment by danesfeder** [comment]
@Guardiola31337 noting that the updated key was pushed and the translations in TX were not erased

**Comment by Guardiola31337** [comment]
> noting that the updated key was pushed and the translations in TX were not erased

Great. Thanks for confirming.

As you pointed out, it seems that Transifex doesn't care about the keys themselves (only the actual words being translated). Apparently, it sees a diff and the actually strings in the XML are the same and then just takes the new key.

We're good here. Thanks @danesfeder for dealing with this.

**Comment by 1ec5** [comment]
> As you pointed out, it seems that Transifex doesn't care about the keys themselves (only the actual words being translated). Apparently, it sees a diff and the actually strings in the XML are the same and then just takes the new key.

On the contrary, keys are what Transifex uses to identify a translation. So if the key is renamed in this repository, it’ll show up as a new, untranslated string across all localizations. Translators would then go in and accept the 💯 match that Transifex suggests thanks to translation memory.

**Comment by Guardiola31337** [comment]
@1ec5 
> On the contrary, keys are what Transifex uses to identify a translation.

That's what I initially thought and I'd expect.

> Translators would then go in and accept the 100 match that Transifex suggests thanks to translation memory.

What about the translations with the old key?

Also, I didn't accept anything. You @danesfeder? Could we know who accepted the match? I ask because apparently in this case was done automatically somehow by Transifex.

**Comment by 1ec5** [comment]
It takes a little while for Transifex to pick up the changes in master. Now that it has picked up the changes, a bunch of localizations have four strings needing translation.

The old translations for `title_navigation_view_ui` will not be suggested for `title_navigation_launcher`, because the new base value “Navigation Launcher” is too different from the original “Navigation Views”. “Navigation Launcher” will need a different translation anyways.

**Comment by Guardiola31337** [comment]
> It takes a little while for Transifex to pick up the changes in master. Now that it has picked up the changes, a bunch of localizations have four strings needing translation.

Ohhhh, that makes sense.

> The old translations for `title_navigation_view_ui` will not be suggested for `title_navigation_launcher`, because the new base value “Navigation Launcher” is too different from the original “Navigation Views”. “Navigation Launcher” will need a different translation anyways.

Correct, I wasn't expecting `title_navigation_view_ui` and `title_navigation_launcher` to match, actually the first key was replaced with the latter. Does that mean that we also need to remove `title_navigation_view_ui` (not valid anymore) somehow? I was wondering what happened with `description_navigation_view_ui` and `description_navigation_launcher`. We only changed the key but not the translations so they match :100: 

Going to reopen #1077 until we ensure that we only have two strings in Transifex - `title_navigation_launcher` needing translations and `description_navigation_launcher` accepting the matches because old and new translations haven't changed at all.

**Pull request merged**
