### PR TITLE
Take screenshot using the existing snapshot API

### PR DESCRIPTION
**Pull request by zugaldia**
This PR combines the existing `snapshot` API to capture the map (including traffic and puck info) combined with regular Android View capturing to obtain a full picture of the current navigation session. This uses an invisible image to temporarily store the map screenshot.

The result looks like:

telemetry

cc: @mapbox/navigation-android @Guardiola31337

### CODE REVIEW

**Comment by zugaldia** [comment]
@danesfeder Absolutely. The current location just simplifies testing, I'll let you decide the final structure for this functionality.

**Comment by danesfeder** [comment]
@ericrwolfe @zugaldia this is hooked up to the UI now and is ready for another round of 👀

**Comment by zugaldia** [comment]
As the original author I cannot approve the PR but current state looks 👍 to me.

**Comment by danesfeder** [comment]
Thanks for the help on this PR @zugaldia! 

@ericrwolfe let's confirm we are getting valid screenshots from this PR, then merge

**Comment by zugaldia** [comment]
I'll merge it as soon as CI approves.

**Pull request merged**
