### PR TITLE
bump NN to 130.1.0

### PR DESCRIPTION
**Pull request by dzinad**

### CODE REVIEW

**Review by averkhaturau — APPROVED** [review]

**Comment by VysotskiVadim** [comment]
@dzinad , can you please remove `@Ignore("Waiting for NN-654 to be fixed")`?

**Comment by dzinad** [comment]
> @dzinad , can you please remove @Ignore("Waiting for NN-654 to be fixed")?

This test is not in the release branch.

**Comment by VysotskiVadim** [comment]
> This test is not in the release branch.

This PR is to main branch, isn't it?

**Comment by dzinad** [comment]
@VysotskiVadim the test I unignored failed. I think it might be because the device is slow and it takes quite a lot of time to process the response. WDYT? Should we increase the timeout?

**Comment by VysotskiVadim** [comment]
> @VysotskiVadim the test I unignored failed. I think it might be because the device is slow and it takes quite a lot of time to process the response. WDYT? Should we increase the timeout?

oh, that's bad. Let's not use it for now then. I will troubleshoot it in an followup PR.

**Review by VysotskiVadim — APPROVED** [review]

**Pull request merged**
