### PR TITLE
Removed access token from RouteOptions

### PR DESCRIPTION
**Pull request by LukasPaczos**
### Description

Integrates changes from https://github.com/mapbox/mapbox-java/pull/1276 and reverts https://github.com/mapbox/mapbox-navigation-android/pull/4667 which suffered from the enforcement of token in `RouteOptions` which is not the case anymore. More context in https://github.com/mapbox/mapbox-java/issues/1275.

### Changelog

```
<changelog>:warning: Removed `accessToken` from `RouteOptions`, the token provided via `NaivgationOptions` is now always used for route requests. This also simplifies serialization and deserialization of route objects. Refs [`mapbox-java` `v6.0.0-alpha2`](https://github.com/mapbox/mapbox-java/releases/tag/v6.0.0-alpha.2).</changelog>
```

### CODE REVIEW

**Comment by Guardiola31337** [comment]
Noting that build is ❌ 

```
> Task :libnavigation-router:compileDebugKotlin FAILED
e: /root/code/libnavigation-router/src/main/java/com/******/navigation/route/internal/offboard/MapboxOffboardRouter.kt: (65, 14): Unresolved reference: accessToken
e: /root/code/libnavigation-router/src/main/java/com/******/navigation/route/internal/onboard/MapboxOnboardRouter.kt: (64, 14): Unresolved reference: accessToken

FAILURE: Build failed with an exception.
```

`Router`s need the new `accessToken` to be passed in.

**Comment by LukasPaczos** [comment]
I built this branch against a local snapshot, it won't compile until we upgrade `mapbox-java`.

**Comment by LukasPaczos** [comment]
This is ready for review.

**Review by korshaknn — APPROVED** [review]
LGTM

**Review by Guardiola31337 — APPROVED** [review]
:shipit:

**Comment by Guardiola31337** [comment]
@LukasPaczos Could we add a note to the `CHANGELOG` warning that previous history files can't be used and may cause crashes if so?

**Comment by LukasPaczos** [comment]
I don't think there will be any problems with the old history files besides what's been mentioned in [`2.0.0-beta.20` changelog](2.0.0-beta.20). Unless you have something else in mind?

**Comment by Guardiola31337** [comment]
Yeah, I tested and run into this 💥 

```
--------- beginning of crash
2021-07-28 10:35:03.229 23246-23246/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 23246
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.routeOptions.coordinates
        at com.google.gson.Gson.fromJson(Gson.java:944)
        at com.google.gson.Gson.fromJson(Gson.java:1003)
        at com.google.gson.Gson.fromJson(Gson.java:975)
        at com.mapbox.api.directions.v5.models.DirectionsRoute.fromJson(DirectionsRoute.java:182)
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.mapDirectionsRoute(HistoryEventMapper.kt:72)
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.mapSetRoute(HistoryEventMapper.kt:60)
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.map(HistoryEventMapper.kt:28)
        at com.mapbox.navigation.core.history.MapboxHistoryReader.loadNext(MapboxHistoryReader.kt:44)
        at com.mapbox.navigation.core.history.MapboxHistoryReader.next(MapboxHistoryReader.kt:38)
        at com.mapbox.navigation.core.history.MapboxHistoryReader.next(MapboxHistoryReader.kt:13)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invokeSuspend(HistoryFileLoader.kt:26)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invoke(Unknown Source:8)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader.loadSelectedHistory(HistoryFileLoader.kt:23)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader.access$loadSelectedHistory(HistoryFileLoader.kt:11)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadReplayHistory$2.invokeSuspend(HistoryFileLoader.kt:19)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.routeOptions.coordinates
        at com.google.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:181)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
        at com.mapbox.api.directions.v5.models.AutoValue_RouteOptions$GsonTypeAdapter.read(AutoValue_RouteOptions.java:417)
        at com.mapbox.api.directions.v5.models.AutoValue_RouteOptions$GsonTypeAdapter.read(AutoValue_RouteOptions.java:36)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsRoute$GsonTypeAdapter.read(AutoValue_DirectionsRoute.java:255)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsRoute$GsonTypeAdapter.read(AutoValue_DirectionsRoute.java:31)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:1003) 
        at com.google.gson.Gson.fromJson(Gson.java:975) 
        at com.mapbox.api.directions.v5.models.DirectionsRoute.fromJson(DirectionsRoute.java:182) 
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.mapDirectionsRoute(HistoryEventMapper.kt:72) 
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.mapSetRoute(HistoryEventMapper.kt:60) 
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.map(HistoryEventMapper.kt:28) 
        at com.mapbox.navigation.core.history.MapboxHistoryReader.loadNext(MapboxHistoryReader.kt:44) 
        at com.mapbox.navigation.core.history.MapboxHistoryReader.next(MapboxHistoryReader.kt:38) 
        at com.mapbox.navigation.core.history.MapboxHistoryReader.next(MapboxHistoryReader.kt:13) 
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) 
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170) 
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) 
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786) 
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816) 
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invokeSuspend(HistoryFileLoader.kt:26) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invoke(Unknown Source:8) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invoke(Unknown Source:4) 
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89) 
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165) 
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader.loadSelectedHistory(HistoryFileLoader.kt:23) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader.access$loadSelectedHistory(HistoryFileLoader.kt:11) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadReplayHistory$2.invokeSuspend(HistoryFileLoader.kt:19) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
```

This is due to new `DirectionsRoute` structure serialization brought from https://github.com/mapbox/mapbox-java/pull/1276

**Comment by LukasPaczos** [comment]
This seems to be one of the changes from https://github.com/mapbox/mapbox-navigation-android/pull/4667 that I reverted but is actually needed anyway :+1:

**Comment by Guardiola31337** [comment]
We added this warning in the release notes:

> :warning: `mapbox-java` `v6.0.0-alpha.1` brought new features but also some breaking changes to `DirectionsRoute` and `MapboxDirections` objects that impact replay.

**Comment by Guardiola31337** [comment]
If you changed something, I pulled the latest changes and it's still failing 💥 

```
2021-07-28 11:01:37.574 25049-25049/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 25049
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.routeOptions.coordinates
        at com.google.gson.Gson.fromJson(Gson.java:944)
        at com.google.gson.Gson.fromJson(Gson.java:1003)
        at com.google.gson.Gson.fromJson(Gson.java:975)
        at com.mapbox.api.directions.v5.models.DirectionsRoute.fromJson(DirectionsRoute.java:182)
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.mapDirectionsRoute(HistoryEventMapper.kt:72)
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.mapSetRoute(HistoryEventMapper.kt:60)
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.map(HistoryEventMapper.kt:28)
        at com.mapbox.navigation.core.history.MapboxHistoryReader.loadNext(MapboxHistoryReader.kt:44)
        at com.mapbox.navigation.core.history.MapboxHistoryReader.next(MapboxHistoryReader.kt:38)
        at com.mapbox.navigation.core.history.MapboxHistoryReader.next(MapboxHistoryReader.kt:13)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invokeSuspend(HistoryFileLoader.kt:26)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invoke(Unknown Source:8)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader.loadSelectedHistory(HistoryFileLoader.kt:23)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader.access$loadSelectedHistory(HistoryFileLoader.kt:11)
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadReplayHistory$2.invokeSuspend(HistoryFileLoader.kt:19)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.routeOptions.coordinates
        at com.google.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:181)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
        at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
        at com.mapbox.api.directions.v5.models.AutoValue_RouteOptions$GsonTypeAdapter.read(AutoValue_RouteOptions.java:417)
        at com.mapbox.api.directions.v5.models.AutoValue_RouteOptions$GsonTypeAdapter.read(AutoValue_RouteOptions.java:36)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsRoute$GsonTypeAdapter.read(AutoValue_DirectionsRoute.java:255)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsRoute$GsonTypeAdapter.read(AutoValue_DirectionsRoute.java:31)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:1003) 
        at com.google.gson.Gson.fromJson(Gson.java:975) 
        at com.mapbox.api.directions.v5.models.DirectionsRoute.fromJson(DirectionsRoute.java:182) 
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.mapDirectionsRoute(HistoryEventMapper.kt:72) 
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.mapSetRoute(HistoryEventMapper.kt:60) 
        at com.mapbox.navigation.core.history.model.HistoryEventMapper.map(HistoryEventMapper.kt:28) 
        at com.mapbox.navigation.core.history.MapboxHistoryReader.loadNext(MapboxHistoryReader.kt:44) 
        at com.mapbox.navigation.core.history.MapboxHistoryReader.next(MapboxHistoryReader.kt:38) 
        at com.mapbox.navigation.core.history.MapboxHistoryReader.next(MapboxHistoryReader.kt:13) 
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) 
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170) 
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) 
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:786) 
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:816) 
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:807) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invokeSuspend(HistoryFileLoader.kt:26) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invoke(Unknown Source:8) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadSelectedHistory$2.invoke(Unknown Source:4) 
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89) 
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165) 
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader.loadSelectedHistory(HistoryFileLoader.kt:23) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader.access$loadSelectedHistory(HistoryFileLoader.kt:11) 
        at com.mapbox.navigation.examples.core.replay.HistoryFileLoader$loadReplayHistory$2.invokeSuspend(HistoryFileLoader.kt:19) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
```

**Review by kmadsen — APPROVED** [review]
💯  💯

**Pull request merged**
