### PR TITLE
Docs monopackage

### PR DESCRIPTION
**Pull request by danswick**
### Description
This PR prepares the `publisher-production` branch to document the single navigation monopackage for versions 1.0.0 and greater.

### CODE REVIEW

**Review by RingerJK — APPROVED** [review]
what is a pattern of storing structure? is it like `navigation/X.Y.Z/` where `X.Y.Z` is version?

**Comment by RingerJK** [comment]
will it be available on [publisher-staging](https://github.com/mapbox/mapbox-navigation-android/tree/publisher-staging) as well?

**Comment by danswick** [comment]
@RingerJK yes, that's exactly right. It should be organized the same way the old `core` and `ui` folders were organized. 

Regarding `publisher-staging`, we could always start there for testing and then merge it into `publisher-production` if that sounds better to you.

**Comment by RingerJK** [comment]
@danswick I'd create the very first docs for staging, just for test

**Comment by danswick** [comment]
@RingerJK after chatting with @katydecorah, I think we might want to put the monopackage contents right in the root instead of inside a `navigation` folder. We would leave the old `ui` and `core` files in place until they are archived so we don't break any links for existing users. So the folder structure would look something like this:

```
mapbox-navigation-android
├── ui
├── core
├── 1.0.0
├── 1.1.0
├── 1.2.0
└── x.x.x
```

What do you think? If this looks good to you, we will need to: 

- [ ] @danswick update the related PR for the documentation page. 
- [ ] @RingerJK rebuild the docs for v1.0.0 and greater as a single package 
- [ ] @danswick archive the old `ui` and `core` docs for v1.0.0 and greater
- [ ] @danswick update redirects for the old `ui` and `core` docs

**Comment by danswick** [comment]
@RingerJK do you think you will have capacity to rebuild the docs v1.0.0 and newer? I think we'll be able to close this out pretty quickly once those are ready!

**Comment by RingerJK** [comment]
@danswick yeah, I'm working with it. Create a new docs pr soon

**Comment by RingerJK** [comment]
Created a very first pull for `publisher-staging` https://github.com/mapbox/mapbox-navigation-android/pull/3908

**Comment by danswick** [comment]
Thanks, @RingerJK! I will check that out now.

Just to make sure we're on the same page, are you also planning to rebuild the past releases? Unless something has changed, I thought we needed to rebuild the following with the new monopackage configuration:

- [ ]  1.1.1
- [ ]  1.0.1
- [ ]  1.0.0

**Comment by RingerJK** [comment]
@danswick yeah, it's a plan 👍  #3908 is the very first. I wanted to make sure that everything is works as expected with **staging**. If we're good with it, I'm ready to rebuild all docs for **production**

**Pull request merged**
