### PR TITLE
change deprecated "flame" device to "oriole" (Pixel 6, 31) on Firebase

### PR DESCRIPTION
**Pull request by LukasPaczos**

### CODE REVIEW

**Review by RingerJK — APPROVED** [review]

**Comment by RingerJK** [comment]
could you make `instrumentation-tests` required again after merge PR 🙇

**Comment by Guardiola31337** [comment]
`multipleSetRouteCall_longAndShortRouteTest` failed

```
java.lang.RuntimeException: Previous set routes call wasn't cancelled as expected.
at com.mapbox.navigation.instrumentation_tests.ui.routeline.SetRouteOrderTest.multipleSetRouteCall_longAndShortRouteTest$lambda-0(SetRouteOrderTest.kt:75)
at com.mapbox.navigation.instrumentation_tests.ui.routeline.SetRouteOrderTest.$r8$lambda$O0zdCYnx3w_naoa_NVvtEz_73L8(Unknown Source:0)
at com.mapbox.navigation.instrumentation_tests.ui.routeline.SetRouteOrderTest$$ExternalSyntheticLambda4.accept(Unknown Source:2)
at com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi$setNavigationRouteLines$1.invokeSuspend(MapboxRouteLineApi.kt:333)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:14)
at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:8)
at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:17)
at androidx.test.espresso.Espresso$1.run(Espresso.java:1)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by RingerJK** [comment]
jfi deprecated devices list https://firebase.google.com/docs/test-lab/android/available-testing-devices#deprecated_devices

**Comment by RingerJK** [comment]
@LukasPaczos looks like changelog PR is made code coverage 77% https://codecov.io/gh/mapbox/mapbox-navigation-android/commit/3b9bbcc97bfc719c168392faf59333c91bf92eda . Looks wired as changelog PR is not run CI. We need to investigate that, but your PR returns back right values of coverage

**Pull request merged**
