### PR TITLE
Fix snap bearing and simplify algo

### PR DESCRIPTION
**Pull request by dsilvera**

### CODE REVIEW

**Comment by danesfeder** [comment]
Hey @dsilvera thanks for another contribution here!  Have you tested this / seen any issues when transitioning between steps?  We had previously ran into issue when, at the end of the step, there weren't any upcoming `Point`s left in the step `LineString` to calculate the bearing.  That's why we would look at the first point of the upcoming step.  

I guess with your logic in that scenario, it will fall back to the `Location#getBearing`?

**Comment by dsilvera** [comment]
The previous algorithm was based on the remaining distance subtracted from the total distance of the step to derive the next location. So distances calculated by app was compared with the total distance sent by the server. It's pretty risky.

The new algorithm builds a LineString with the next points and we deduce the next location. It's more reliable and simpler. No more distance notion.

I have tested this on real case and with the simulator.

It will fall back to the snap location bearing.

**Comment by danesfeder** [comment]
@dsilvera yeah this algorithm is much simpler, I agree.  Thanks!  I've added it to the list for review - the review process will be just like your previous contribution.

**Comment by danesfeder** [comment]
Hey @dsilvera sorry for the delay here - we will look at this early next week.  Thanks for your patience!

**Comment by boldtrn** [comment]
Thanks @dsilvera for providing this PR. I have sometimes seen issues with the bearing snap as well. I tried this PR and it seems a lot easier to understand and more robust. @danesfeder did you have the chance to have a look at this PR? Is there anything that needs to be improved?

**Comment by danesfeder** [comment]
Hey 👋 @boldtrn @dsilvera - this logic has been removed in the `0.20.0` update - do you mind re-testing / closing here if found sufficient?  Thanks!

**Comment by boldtrn** [comment]
Thanks for letting me know @danesfeder. The issues I have seen with route snapping seems to have been resolved with `0.20.0`.

**Comment by danesfeder** [comment]
Hey @dsilvera, I'm going to go ahead and close this PR, as the code contributed is no longer used in our SDK logic.  Thanks again for the contribution.  We always appreciate contributions and improvements to the SDK 🙏 

If you find any other issues or improvements, please feel free to follow up.  Thanks!

**Pull request closed without merging**
