### PR TITLE
Updated test to use non-deprecated route line calls.

### PR DESCRIPTION
**Pull request by cafesilencio**
### Description
Updated test to use non-deprecated route line calls.  There was some flakiness in the SetRouteOrderTest perhaps introduced by a caching mechanism for parsing routes via the `NavigationRoute` class.

### CODE REVIEW

**Comment by Guardiola31337** [comment]
It seems this is not solving the flakiness, it failed again https://console.firebase.google.com/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/5729712389931682553/executions/bs.d9586fd0372da7c5/test-cases 🤔

**Comment by cafesilencio** [comment]
This is why I made it a draft PR to start with.  I'll keep working on this.

**Comment by cafesilencio** [comment]
That at least is a different error. That could be helpful.

**Review by Guardiola31337 — APPROVED** [review]
Thanks for taking care of this @cafesilencio 🙇‍♂️

**Pull request merged**
