### PR TITLE
Update translations to latest Transifex

### LINKED ISSUE #2000: Mapbox localization
Can u please pull in the yoruba language i translated in transifex

### PR DESCRIPTION
**Pull request by Guardiola31337**
## Description

Updates translations to latest Transifex

Fixes #2000 

- [x] I have added any issue links
- [x] I have added all related labels (`bug`, `feature`, `new API(s)`, `SEMVER`, etc.)
- [x] I have added the appropriate milestone and project boards

### Goal

Get newest and latest translations available in Transifex

### Implementation

Pull translations from Transifex and add them to the SDK and test app

## Testing

Please describe the manual tests that you ran to verify your changes

- [x] I have tested locally (including `SNAPSHOT` upstream dependencies if needed) through testapp/demo app and run all activities to avoid regressions
- [x] New and existing unit tests pass locally with my changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have updated the `CHANGELOG` including this PR
- [x] Any changes to strings have been published to our translation tool

cc @toblinkz

### CODE REVIEW

**Comment by toblinkz** [comment]
Please can u tag the yoruba translation in the PR that updates them so they
will be available in the next release.

**Comment by Guardiola31337** [comment]
@toblinkz 
> Please can u tag the yoruba translation in the PR that updates them so they
will be available in the next release.

Not sure what you mean by ☝️ 

Are you referring to https://github.com/Project-OSRM/osrm-text-instructions/pull/284

All translations added in OP will be available in the next release. Translations added in ☝️ will be available as soon as that PR gets merged, as my colleague @1ec5 described in https://github.com/mapbox/mapbox-navigation-android/issues/2000#issuecomment-513310745

> Once that PR is merged, we can do a release and deployment with the new translations. (The translations are deployed on the server side, so you won’t need to wait for a new navigation SDK release.)

**Comment by toblinkz** [comment]
Sorry what's the PR and how do I access it

**Comment by Guardiola31337** [comment]
@toblinkz 
> Sorry what's the PR and how do I access it

I believe you're referring to https://github.com/Project-OSRM/osrm-text-instructions/pull/284 If so, you can comment freely in there. Actually, there are a couple of comments / questions that would be 💯 if you can answer back 🙏 https://github.com/Project-OSRM/osrm-text-instructions/pull/284#pullrequestreview-264336520 https://github.com/Project-OSRM/osrm-text-instructions/pull/284#discussion_r305451609

**Comment by toblinkz** [comment]
Any help on building on a TTS engine for the Yoruba translation

**Pull request merged**
