### PR TITLE
docs v1.1.0-alpha.2

### PR DESCRIPTION
**Pull request by RingerJK**
### Description

Docs for `v1.1.0-alpha.2`

### CODE REVIEW

**Comment by RingerJK** [comment]
@danswick could you provide solution to format docs according mapbox styles

**cc** @colleenmcginnis

**Comment by danswick** [comment]
@RingerJK, I pushed a few commits to this branch that get us part of the way there: 

* https://github.com/mapbox/mapbox-navigation-android/pull/3785/commits/cd36ae0a6f6bf20e3a71cd1f09314178d4d23783 catches up with `publisher-production`, to which I added a formatting script earlier today in https://github.com/mapbox/mapbox-navigation-android/pull/3788.
* https://github.com/mapbox/mapbox-navigation-android/pull/3785/commits/f9e2abdc44dc35e54f949588e5d0f9be0553d3e3 formats the ui and core docs you added using the formatting script.
* https://github.com/mapbox/mapbox-navigation-android/pull/3785/commits/8b24e716bad159870af22fa554d7983381be0549 adds some changes to the way we handle CSS. 

⚠️ Note: I noticed that ui and core pages look for their stylesheets in different places: 
* UI always looks in `ui/1.1.0-alpha.2/style.css`. 
* Core always looks one directory deeper than UI, which would require adding a `style.css` file to every subdirectory. For example, `core/1.1.0-alpha.2/libnavigation-core/style.css`. 

It would be ideal if both could just look in their parent directories (for example, `/ui/style.css`). If that is not possible, can you tweak Dokka so that it generates Core files the same way it generates UI files?

**Comment by Guardiola31337** [comment]
Where are we here @danswick? Could you provide an update when you have a chance? 🙏

**Comment by danswick** [comment]
@Guardiola31337 I have prepared a docs site PR here: https://github.com/mapbox/android-docs/pull/1599. There are a couple of prerequisites we'll need to address (bulleted out in the PR) before this can merge.

**Comment by RingerJK** [comment]
Not actual version anymore

**Pull request closed without merging**
