### PR TITLE
[grsmto] Fix multi-legs routes

### PR DESCRIPTION
**Pull request by cammace**
I've pulled in https://github.com/mapbox/mapbox-navigation-android/pull/109 so that CI can run on this PR.

### CODE REVIEW

**Comment by cammace** [comment]
I add support for multiple waypoints (more than origin and destination) in `MapboxNavigation` and fixed up `RouteProgress` to consider legs when doing calculations. I'd feel more comfortable with this PR getting merged once test are added. Particularly to the RouteProgress models where I caught the distanceTraveled not being calculated correctly with more than one leg. 

Besides the test, the mock location engine wasn't considering routes with multiple legs either. https://github.com/mapbox/mapbox-java/pull/496 fixes this issue and will need to be merged before this one.

**Comment by 1ec5** [comment]
By the way, you can force Bitrise to build for a contributed PR like #109 by pushing an identically named branch (in this case, `Grsmto-multi-legs-support`) to this repository. GitHub will use that branch’s build status until a commit is pushed to the branch on the fork.

**Comment by 1ec5** [comment]
This fixes #27.

**Comment by cammace** [comment]
Added a new fixture with multiple route legs and a handful of test to ensure the RouteProgress calculations are working as expected. Requesting @danesfeder's review for extra 👀

**Comment by cammace** [comment]
This PR also adds a check to ensure snap to route doesn't try getting a point on the route when the geometry doesn't exist closing https://github.com/mapbox/mapbox-navigation-android/issues/83.

**Pull request merged**
