### PR TITLE
Add example with MapboxNavigation driving separate UI components

### PR DESCRIPTION
**Pull request by danesfeder**
Adds an example to the test application demonstrating `MapboxNavigation` setup / updating an `InstructionView` + `NavigationMapboxMap`

Currently uses default styling for map, instruction view, and route line.

ezgif com-video-to-gif

cc @nitaliano @d-prukop @bsudekum

### CODE REVIEW

**Comment by nitaliano** [comment]
I think we should

* Disable being able to long press while we are in a navigation mode
* Add a floating cancel button to exit navigation

**Comment by danesfeder** [comment]
@Guardiola31337 this is also ready for review unless @nitaliano you have anything else to add here

**Comment by nitaliano** [comment]
I'm good on my end

**Comment by danesfeder** [comment]
@Guardiola31337 this is updated and ready for another round of 👀 

> Are all the comments in ComponentNavigationActivity really necessary?

I know what you're saying with regard to the comments, but I think it's okay to be overly verbose in these test applications.  As developers look to implement the SDK and see these examples, I believe they will make things a little more clear.  

> In general, we should keep public methods as clean as possible so they read like pseudocode (i.e. no conditionals, fors, etc.).

FWIW, in addition to the extra comments in the code, most of the `public` methods in this example are using extracted `private` methods that are explaining their purpose (or at least, I tried to name them this way).

**Pull request merged**
