### PR TITLE
Don't conflate coordinates and waypoints

### PR DESCRIPTION
**Pull request by dudeuter**
### Description
Fixes issues with silent waypoints, routes from the EV route planner, and BYOR.

### CODE REVIEW

**Comment by LukasPaczos** [comment]
Tagging @RingerJK as you've been working on https://github.com/mapbox/mapbox-navigation-android/pull/6005 which essentially tackles the same problem (and more).

**Comment by RingerJK** [comment]
#6005 is ready for review, we should be good to close this one if merge #6005

**Comment by kmadsen** [comment]
@dudeuter will you add tests for this?

**Comment by dudeuter** [comment]
> @dudeuter will you add tests for this?

@RingerJK's work will make this change unnecessary in v2.9+ I was working on this as more of a workaround for [this part of the Java SDK](https://github.com/mapbox/mapbox-java/blob/796f12d795da9816e26531395060277ba1216547/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java#L969-L972) not decoding the URL properly.

We might want to update the RouteOptions index URL Path parameters starting from the end.

```Java
List<String> pathElements = Arrays.asList(url.getPath().split("/"));
Collections.reverse(pathElements);

optionsJson.addProperty("coordinates", URLDecoder.decode(pathElements.get(0), UTF_8));
optionsJson.addProperty("profile", URLDecoder.decode(pathElements.get(1), UTF_8));
optionsJson.addProperty("user", URLDecoder.decode(pathElements.get(2), UTF_8));
```

That way if anyone's messing around with the basepath they'll be more likely to correctly parse their coordinates, and they can next their API as many arbitrary paths as they want.

**Comment by LukasPaczos** [comment]
Since https://github.com/mapbox/mapbox-navigation-android/pull/6005 landed, changes here are not needed anymore.

@dudeuter let's start a separate ticket/PR if you think we should make any changes to how we parse URLs.

**Pull request closed without merging**
